// VIVEDFX English Translations
// Auto-generated language file

window.EN = {
  // Navigation
  nav_services: "Services",
  nav_portfolio: "Portfolio",
  nav_industries: "Industries",
  nav_process: "Process",
  nav_clients: "Clients",
  nav_book_call: "Book a Call",

  // Hero Section
  hero_label: "Marketing Agency",
  hero_title_1: "We Build",
  hero_title_2: "Brands",
  hero_title_3: "People Remember",
  hero_sub: "We transform ideas into attention, trust, and measurable business growth through creative strategy and performance marketing.",
  hero_cta_1: "Book Strategy Call",
  hero_cta_2: "View Portfolio",
  hero_stat_1_num: "+150",
  hero_stat_1_label: "Clients Worldwide",
  hero_stat_2_num: "98%",
  hero_stat_2_label: "Client Retention",
  hero_stat_3_num: "3.8x",
  hero_stat_3_label: "Average ROI",

  // Marquee
  marquee_1: "Social Media",
  marquee_2: "Brand Identity",
  marquee_3: "Video Editing",
  marquee_4: "Paid Ads",
  marquee_5: "Graphic Design",
  marquee_6: "Web Design",
  marquee_7: "Videography",
  marquee_8: "Photography",
  marquee_9: "Media Buying",

  // Services Section
  services_label: "What We Do",
  services_title: "Services That Drive Results",
  services_title_accent: "",
  services_desc: "Everything your brand needs to grow, convert, and dominate.",

  // Portfolio Section
  portfolio_label: "Our Work",
  portfolio_title: "Results We've Delivered",
  portfolio_title_accent: "",
  portfolio_all: "All",
  portfolio_medical: "Medical",
  portfolio_fitness: "Fitness",
  portfolio_corporate: "Corporate",

  // Stats Section
  stats_label: "Average Client Results",
  stats_title: "Results",
  stats_title_accent: "We've Delivered",

  // Industries Section
  ind_label: "Who We Serve",
  ind_title: "Industries We Specialize In",
  ind_title_accent: "",
  ind_1: "Doctors & Clinics",
  ind_2: "Gyms & Fitness Studios",
  ind_3: "Engineering Companies",
  ind_4: "Corporate Businesses",
  ind_5: "Restaurants & F&B",
  ind_6: "Teachers & Educational Centers",

  // Process Section
  process_label: "How We Work",
  process_title: "Our Process",
  process_title_accent: "",
  process_1_title: "Discovery",
  process_1_desc: "Deep dive into your business, competitors, and target audience to understand what truly differentiates you.",
  process_2_title: "Strategy",
  process_2_desc: "Custom roadmap built around your goals — what channels, what content, what budget will drive maximum results.",
  process_3_title: "Production",
  process_3_desc: "World-class creative execution — content, design, video, copy — all produced to the highest standard by our in-house team.",
  process_4_title: "Launch",
  process_4_desc: "Precision deployment across platforms — every post, ad, and asset published at the optimal time for maximum impact.",

  // Testimonials Section
  test_label: "Client Love",
  test_title: "What Our Clients Say",
  test_title_accent: "",
  test_1_text: "vivedfx completely transformed our clinic's online presence. In 4 months, we went from almost no social engagement to 40,000+ monthly impressions. New patient bookings are up 3x and our brand finally looks as professional as our service.",
  test_1_name: "Dr. Ahmed Hassan",
  test_1_role: "Founder, MediCare Plus Clinic",
  test_2_text: "Our gym membership doubled in 6 months after vivedfx launched our rebrand and ad campaigns. The creative work is absolutely fire — our community loves the content and our competitors are clearly watching us now. Best investment we've ever made.",
  test_2_name: "Sarah Mitchell",
  test_2_role: "Owner, IronEdge Fitness",
  test_3_text: "As an engineering firm, we struggled to communicate what we do in a compelling way. vivedfx built us a brand we're genuinely proud of and a website that generates real inbound leads. Revenue from digital channels is up over 200% year-over-year.",
  test_3_name: "James Okonkwo",
  test_3_role: "CEO, BuildCore Engineering",

  // CTA Section
  cta_title: "Ready To Grow Your Business?",
  cta_title_accent: "",
  cta_sub: "Book a free strategy call today. No pressure, no obligation — just a clear plan for your brand's growth.",
  cta_btn: "Book Free Consultation",

  // Footer
  footer_desc: "We build brands people remember. Premium marketing agency serving businesses that demand results.",
  footer_services: "Services",
  footer_industries: "Industries",
  footer_start_project: "Start A Project",
  footer_rights: "\u00a9 2026 VIVEDFX. All rights reserved. Built for brands that mean business.",
  footer_privacy: "Privacy Policy",
  footer_terms: "Terms of Service",

  // Common Buttons
  back_to_home: "Back to Home",
  view_full_details: "View Full Details",
  prev_service: "Previous Service",
  next_service: "Next Service",
  book_free_call: "Book Free Strategy Call",
  contact_whatsapp: "Contact Us on WhatsApp",
  svc_start_brief: "Start Brief",

  // Service Overview Cards
  sv_1_title: "Social Media Management",
  sv_1_desc: "Strategic content creation, community management, and analytics that build audiences and drive engagement.",
  sv_2_title: "Brand Identity",
  sv_2_desc: "Complete visual systems — logos, color palettes, typography, brand guidelines.",
  sv_3_title: "Video Editing",
  sv_3_desc: "Cinematic reels, brand films, testimonials, and short-form content optimized for maximum reach.",
  sv_4_title: "Graphic Design",
  sv_4_desc: "Visuals that stop the scroll — ads, banners, print, packaging crafted to convert.",
  sv_5_title: "Paid Advertising",
  sv_5_desc: "Data-driven Meta, Google, and TikTok ad campaigns engineered for maximum ROI.",
  sv_6_title: "Website Design",
  sv_6_desc: "High-converting, fast, and beautiful websites built to turn visitors into customers.",
  sv_7_title: "Cinematic Videography",
  sv_7_desc: "Professional on-ground video production — corporate shoots, events, product videos.",
  sv_8_title: "Commercial Photography",
  sv_8_desc: "High-quality product, portrait, and commercial photography.",
  sv_9_title: "Strategic Media Buying",
  sv_9_desc: "Strategic media planning and buying across TV, digital, and out-of-home channels.",

  // ==================== SERVICES PAGE ====================
  svc_page_title: "Everything Your Brand Needs to Grow",
  svc_page_desc: "From strategy to production, we deliver end-to-end creative and marketing services that build brands, drive leads, and scale businesses across every channel.",
  svc_cta_title: "Ready to Get Started?",
  svc_cta_desc: "Book a free strategy call and we'll show you exactly how we'd grow your business across every channel.",
  svc_cta_btn: "Book Free Consultation",

  // ==================== PORTFOLIO PAGE ====================
  port_page_title: "Our Portfolio",
  port_page_desc: "Browse our work across industries.",

  // ==================== SOCIAL MEDIA (sm) ====================
  sm_hero_title: "Social Media Management",
  sm_hero_desc: "Strategic content creation, community management, and analytics that build audiences and drive engagement.",
  sm_why_title: "Why Choose Us",
  sm_stat_1_num: "+420%",
  sm_stat_1_label: "Engagement Increase",
  sm_stat_2_num: "3.8x",
  sm_stat_2_label: "Follower Growth",
  sm_stat_3_num: "90 days",
  sm_stat_3_label: "To Measurable Results",
  sm_deliver_title: "What We Deliver",
  sm_deliver_1: "Content Strategy — Full monthly content calendars tailored to your brand voice.",
  sm_deliver_2: "Daily Posting — Consistent posting across all platforms.",
  sm_deliver_3: "Community Management — Responding to comments and DMs.",
  sm_deliver_4: "Monthly Analytics — Detailed performance insights.",
  sm_deliver_5: "Visual Content Creation — Scroll-stopping graphics and carousels.",
  sm_deliver_6: "Hashtag Research — Strategic hashtag sets for maximum reach.",
  sm_process_title: "Our Process",
  sm_process_1: "Audit",
  sm_process_2: "Strategy",
  sm_process_3: "Create",
  sm_process_4: "Publish",
  sm_process_5: "Optimize",
  sm_benefits_title: "Results & Benefits",
  sm_benefits_1: "More Engaged Followers",
  sm_benefits_2: "Stronger Brand Authority",
  sm_benefits_3: "Higher Website Traffic",
  sm_benefits_4: "Better Customer Relationships",
  sm_benefits_5: "Time Freedom",
  sm_benefits_6: "Data-Driven Growth",
  sm_faq_title: "Frequently Asked Questions",
  sm_faq_1_q: "Which platforms do you manage?",
  sm_faq_1_a: "We manage Instagram, Facebook, TikTok, LinkedIn, Twitter/X, Pinterest, and YouTube.",
  sm_faq_2_q: "How many posts do you create per month?",
  sm_faq_2_a: "Depending on your plan, we create 15-30+ posts per month.",
  sm_faq_3_q: "Do you handle paid advertising too?",
  sm_faq_3_a: "Yes, we offer paid ad management as an add-on service.",
  sm_faq_4_q: "How soon will I see results?",
  sm_faq_4_a: "Most clients see increased engagement within 2-4 weeks.",
  sm_faq_5_q: "Can I approve content before it's posted?",
  sm_faq_5_a: "Absolutely. We send content calendars for your approval before publishing.",
  sm_faq_6_q: "Do you write captions and hashtags too?",
  sm_faq_6_a: "Yes, every post includes professional captions and strategically researched hashtags.",
  sm_cta_title: "Ready to Grow?",
  sm_cta_btn: "Book Free Strategy Call",
  sm_cta_whatsapp: "Contact on WhatsApp",

  // ==================== BRAND IDENTITY (bi) ====================
  bi_hero_title: "Brand Identity",
  bi_hero_desc: "Complete visual systems — logos, color palettes, typography, brand guidelines.",
  bi_why_title: "Why Choose Us",
  bi_stat_1_num: "+380%",
  bi_stat_1_label: "Brand Recognition",
  bi_stat_2_num: "2.5x",
  bi_stat_2_label: "Trust Score Increase",
  bi_stat_3_num: "30 days",
  bi_stat_3_label: "Full Brand Delivery",
  bi_deliver_title: "What We Deliver",
  bi_deliver_1: "Logo Design — Primary, secondary, and icon versions.",
  bi_deliver_2: "Color System — Primary, secondary, and neutral palettes.",
  bi_deliver_3: "Typography — Curated font pairings with hierarchy rules.",
  bi_deliver_4: "Brand Guidelines — Comprehensive consistency document.",
  bi_deliver_5: "Business Cards & Stationery — Complete print collateral.",
  bi_deliver_6: "Brand Pattern & Graphics — Visual elements for all touchpoints.",
  bi_process_title: "Our Process",
  bi_process_1: "Research",
  bi_process_2: "Moodboard",
  bi_process_3: "Design",
  bi_process_4: "Refine",
  bi_process_5: "Deliver",
  bi_benefits_title: "Results & Benefits",
  bi_benefits_1: "Instant Brand Recognition",
  bi_benefits_2: "Professional Market Positioning",
  bi_benefits_3: "Consistent Visual Identity",
  bi_benefits_4: "Increased Customer Trust",
  bi_benefits_5: "Competitive Advantage",
  bi_benefits_6: "Long-term Brand Value",
  bi_faq_title: "Frequently Asked Questions",
  bi_faq_1_q: "How long does brand identity take?",
  bi_faq_1_a: "Typically 2-4 weeks from discovery to final delivery.",
  bi_faq_2_q: "Do I own the final designs?",
  bi_faq_2_a: "Yes, you receive full ownership of all files and source documents.",
  bi_faq_3_q: "How many revisions are included?",
  bi_faq_3_a: "We include up to 3 rounds of revisions in every project.",
  bi_faq_4_q: "What file formats do I receive?",
  bi_faq_4_a: "AI, EPS, PDF, PNG, JPG, and SVG in all color variations.",
  bi_faq_5_q: "Can you work with my existing brand?",
  bi_faq_5_a: "Yes, we can refresh and elevate your existing brand identity.",
  bi_faq_6_q: "Do you create brand guidelines?",
  bi_faq_6_a: "Yes, every project includes a comprehensive brand guidelines document.",
  bi_cta_title: "Ready to Grow?",
  bi_cta_btn: "Book Free Strategy Call",
  bi_cta_whatsapp: "Contact on WhatsApp",

  // ==================== VIDEO EDITING (ve) ====================
  ve_hero_title: "Video Editing",
  ve_hero_desc: "Cinematic reels, brand films, testimonials, and short-form content optimized for maximum reach.",
  ve_why_title: "Why Choose Us",
  ve_stat_1_num: "+500%",
  ve_stat_1_label: "View Increase",
  ve_stat_2_num: "4.2x",
  ve_stat_2_label: "Watch Time Growth",
  ve_stat_3_num: "7 days",
  ve_stat_3_label: "Fast Turnaround",
  ve_deliver_title: "What We Deliver",
  ve_deliver_1: "Reels & Short-form — Scroll-stopping vertical content.",
  ve_deliver_2: "Brand Films — Cinematic storytelling for your brand.",
  ve_deliver_3: "Testimonials — Professional customer review videos.",
  ve_deliver_4: "Motion Graphics — Animated overlays and transitions.",
  ve_deliver_5: "Color Grading — Professional cinematic color correction.",
  ve_deliver_6: "Sound Design — Music selection and audio mixing.",
  ve_process_title: "Our Process",
  ve_process_1: "Brief",
  ve_process_2: "Edit",
  ve_process_3: "Review",
  ve_process_4: "Refine",
  ve_process_5: "Deliver",
  ve_benefits_title: "Results & Benefits",
  ve_benefits_1: "Higher Engagement Rates",
  ve_benefits_2: "Professional Brand Image",
  ve_benefits_3: "Increased Watch Time",
  ve_benefits_4: "Better Content Performance",
  ve_benefits_5: "Time Savings",
  ve_benefits_6: "Platform-Optimized Content",
  ve_faq_title: "Frequently Asked Questions",
  ve_faq_1_q: "What video formats do you deliver?",
  ve_faq_1_a: "We deliver MP4, MOV, and platform-specific formats optimized for each channel.",
  ve_faq_2_q: "How long does a typical edit take?",
  ve_faq_2_a: "Standard edits take 3-5 business days. Rush delivery is available.",
  ve_faq_3_q: "Do you provide revisions?",
  ve_faq_3_a: "Yes, we include up to 3 rounds of revisions with every project.",
  ve_faq_4_q: "Can you match my brand style?",
  ve_faq_4_a: "Absolutely. We adapt our editing style to match your brand guidelines.",
  ve_faq_5_q: "Do you handle voiceovers?",
  ve_faq_5_a: "Yes, we can arrange professional voiceover services in multiple languages.",
  ve_faq_6_q: "What if I need ongoing video editing?",
  ve_faq_6_a: "We offer monthly retainer packages for continuous video content needs.",
  ve_cta_title: "Ready to Grow?",
  ve_cta_btn: "Book Free Strategy Call",
  ve_cta_whatsapp: "Contact on WhatsApp",

  // ==================== GRAPHIC DESIGN (gd) ====================
  gd_hero_title: "Graphic Design",
  gd_hero_desc: "Visuals that stop the scroll — ads, banners, print, packaging crafted to convert.",
  gd_why_title: "Why Choose Us",
  gd_stat_1_num: "+350%",
  gd_stat_1_label: "Conversion Increase",
  gd_stat_2_num: "2.8x",
  gd_stat_2_label: "Click-Through Rate",
  gd_stat_3_num: "48 hours",
  gd_stat_3_label: "Quick Delivery",
  gd_deliver_title: "What We Deliver",
  gd_deliver_1: "Social Media Graphics — Posts, stories, and covers.",
  gd_deliver_2: "Ad Creatives — Banners and display ads.",
  gd_deliver_3: "Print Design — Brochures, flyers, and posters.",
  gd_deliver_4: "Packaging Design — Product packaging and labels.",
  gd_deliver_5: "Presentation Design — Professional slide decks.",
  gd_deliver_6: "Icon Sets — Custom icon libraries.",
  gd_process_title: "Our Process",
  gd_process_1: "Concept",
  gd_process_2: "Design",
  gd_process_3: "Review",
  gd_process_4: "Refine",
  gd_process_5: "Deliver",
  gd_benefits_title: "Results & Benefits",
  gd_benefits_1: "Professional Visual Identity",
  gd_benefits_2: "Higher Conversion Rates",
  gd_benefits_3: "Consistent Brand Presentation",
  gd_benefits_4: "Faster Content Production",
  gd_benefits_5: "Multi-Format Delivery",
  gd_benefits_6: "Scalable Design Systems",
  gd_faq_title: "Frequently Asked Questions",
  gd_faq_1_q: "What design formats do you provide?",
  gd_faq_1_a: "PSD, AI, PDF, PNG, JPG, and source files as requested.",
  gd_faq_2_q: "How many concepts do you present?",
  gd_faq_2_a: "We typically present 2-3 concepts per project for your selection.",
  gd_faq_3_q: "Do you offer rush design services?",
  gd_faq_3_a: "Yes, we offer expedited delivery for urgent projects at an additional fee.",
  gd_faq_4_q: "Can you match my existing brand guidelines?",
  gd_faq_4_a: "Absolutely. We ensure all designs align with your brand standards.",
  gd_faq_5_q: "Do you provide print-ready files?",
  gd_faq_5_a: "Yes, all print designs include CMYK files with bleed and crop marks.",
  gd_faq_6_q: "What if I need design revisions later?",
  gd_faq_6_a: "We offer flexible revision packages for ongoing design needs.",
  gd_cta_title: "Ready to Grow?",
  gd_cta_btn: "Book Free Strategy Call",
  gd_cta_whatsapp: "Contact on WhatsApp",

  // ==================== PAID ADVERTISING (pa) ====================
  pa_hero_title: "Paid Advertising",
  pa_hero_desc: "Data-driven Meta, Google, and TikTok ad campaigns engineered for maximum ROI.",
  pa_why_title: "Why Choose Us",
  pa_stat_1_num: "4.5x",
  pa_stat_1_label: "Average ROAS",
  pa_stat_2_num: "-40%",
  pa_stat_2_label: "Cost Per Acquisition",
  pa_stat_3_num: "+280%",
  pa_stat_3_label: "Revenue Growth",
  pa_deliver_title: "What We Deliver",
  pa_deliver_1: "Campaign Strategy — Full-funnel advertising plans.",
  pa_deliver_2: "Ad Creation — Copy, visuals, and video ads.",
  pa_deliver_3: "Audience Targeting — Precision demographic targeting.",
  pa_deliver_4: "A/B Testing — Continuous creative optimization.",
  pa_deliver_5: "Performance Reports — Weekly analytics and insights.",
  pa_deliver_6: "Retargeting — Win-back campaigns for lost visitors.",
  pa_process_title: "Our Process",
  pa_process_1: "Audit",
  pa_process_2: "Strategy",
  pa_process_3: "Launch",
  pa_process_4: "Optimize",
  pa_process_5: "Scale",
  pa_benefits_title: "Results & Benefits",
  pa_benefits_1: "Lower Cost Per Click",
  pa_benefits_2: "Higher Conversion Rates",
  pa_benefits_3: "Better Return on Ad Spend",
  pa_benefits_4: "Qualified Lead Generation",
  pa_benefits_5: "Scalable Ad Campaigns",
  pa_benefits_6: "Data-Driven Decisions",
  pa_faq_title: "Frequently Asked Questions",
  pa_faq_1_q: "Which ad platforms do you manage?",
  pa_faq_1_a: "Meta (Facebook/Instagram), Google Ads, TikTok Ads, and LinkedIn Ads.",
  pa_faq_2_q: "What's the minimum ad budget?",
  pa_faq_2_a: "We recommend a minimum of $1,000/month for effective campaigns.",
  pa_faq_3_q: "How do you measure campaign success?",
  pa_faq_3_a: "We track ROAS, CPA, CTR, conversions, and custom KPIs aligned with your goals.",
  pa_faq_4_q: "How often will I receive reports?",
  pa_faq_4_a: "Weekly performance reports with monthly comprehensive reviews.",
  pa_faq_5_q: "Can I pause campaigns anytime?",
  pa_faq_5_a: "Yes, you have full control and can pause or adjust campaigns at any time.",
  pa_faq_6_q: "Do you handle ad creative production?",
  pa_faq_6_a: "Yes, we create all ad copy, visuals, and video content in-house.",
  pa_cta_title: "Ready to Grow?",
  pa_cta_btn: "Book Free Strategy Call",
  pa_cta_whatsapp: "Contact on WhatsApp",

  // ==================== WEBSITE DESIGN (wd) ====================
  wd_hero_title: "Website Design",
  wd_hero_desc: "High-converting, fast, and beautiful websites built to turn visitors into customers.",
  wd_why_title: "Why Choose Us",
  wd_stat_1_num: "+450%",
  wd_stat_1_label: "Conversion Increase",
  wd_stat_2_num: "99%",
  wd_stat_2_label: "Uptime Guarantee",
  wd_stat_3_num: "14 days",
  wd_stat_3_label: "Fast Delivery",
  wd_deliver_title: "What We Deliver",
  wd_deliver_1: "Custom Design — Unique layouts tailored to your brand.",
  wd_deliver_2: "Responsive Development — Mobile-first approach.",
  wd_deliver_3: "SEO Optimization — On-page technical SEO.",
  wd_deliver_4: "CMS Integration — Easy content management.",
  wd_deliver_5: "E-commerce Setup — Full online store configuration.",
  wd_deliver_6: "Speed Optimization — Fast loading performance.",
  wd_process_title: "Our Process",
  wd_process_1: "Discovery",
  wd_process_2: "Wireframe",
  wd_process_3: "Design",
  wd_process_4: "Develop",
  wd_process_5: "Launch",
  wd_benefits_title: "Results & Benefits",
  wd_benefits_1: "Higher Conversion Rates",
  wd_benefits_2: "Better User Experience",
  wd_benefits_3: "Improved SEO Rankings",
  wd_benefits_4: "Mobile-First Design",
  wd_benefits_5: "Fast Loading Speed",
  wd_benefits_6: "Easy Content Management",
  wd_faq_title: "Frequently Asked Questions",
  wd_faq_1_q: "What website platforms do you build on?",
  wd_faq_1_a: "WordPress, Shopify, custom HTML/CSS/JS, and headless CMS solutions.",
  wd_faq_2_q: "How long does a website take to build?",
  wd_faq_2_a: "Typically 2-6 weeks depending on complexity and scope.",
  wd_faq_3_q: "Do you provide hosting?",
  wd_faq_3_a: "We can set up and manage hosting for you, or work with your preferred provider.",
  wd_faq_4_q: "Will my website be mobile-friendly?",
  wd_faq_4_a: "Absolutely. All our websites are responsive and mobile-optimized.",
  wd_faq_5_q: "Do you offer website maintenance?",
  wd_faq_5_a: "Yes, we provide ongoing maintenance and support packages.",
  wd_faq_6_q: "Can I update the website myself?",
  wd_faq_6_a: "Yes, we build on user-friendly CMS platforms and provide training.",
  wd_cta_title: "Ready to Grow?",
  wd_cta_btn: "Book Free Strategy Call",
  wd_cta_whatsapp: "Contact on WhatsApp",

  // ==================== VIDEOGRAPHY (vg) ====================
  vg_hero_title: "Cinematic Videography",
  vg_hero_desc: "Professional on-ground video production — corporate shoots, events, product videos.",
  vg_why_title: "Why Choose Us",
  vg_stat_1_num: "+600%",
  vg_stat_1_label: "Engagement Boost",
  vg_stat_2_num: "3.5x",
  vg_stat_2_label: "Brand Recall Increase",
  vg_stat_3_num: "5 days",
  vg_stat_3_label: "Quick Turnaround",
  vg_deliver_title: "What We Deliver",
  vg_deliver_1: "Corporate Videos — Professional business content.",
  vg_deliver_2: "Event Coverage — Full event documentation.",
  vg_deliver_3: "Product Videos — Showcase your products in action.",
  vg_deliver_4: "Brand Storytelling — Cinematic brand narratives.",
  vg_deliver_5: "Interview Videos — Professional talking head content.",
  vg_deliver_6: "Drone Footage — Aerial perspectives.",
  vg_process_title: "Our Process",
  vg_process_1: "Planning",
  vg_process_2: "Production",
  vg_process_3: "Post-Production",
  vg_process_4: "Review",
  vg_process_5: "Deliver",
  vg_benefits_title: "Results & Benefits",
  vg_benefits_1: "Professional Production Quality",
  vg_benefits_2: "Memorable Brand Content",
  vg_benefits_3: "Versatile Content Library",
  vg_benefits_4: "Higher Audience Engagement",
  vg_benefits_5: "Multi-Platform Content",
  vg_benefits_6: "Long-Lasting Visual Assets",
  vg_faq_title: "Frequently Asked Questions",
  vg_faq_1_q: "What video formats do you deliver?",
  vg_faq_1_a: "4K, 1080p, and platform-specific formats in MP4, MOV, and ProRes.",
  vg_faq_2_q: "Do you provide the production crew?",
  vg_faq_2_a: "Yes, we handle all production needs including crew, equipment, and logistics.",
  vg_faq_3_q: "How many revision rounds are included?",
  vg_faq_3_a: "We include up to 3 revision rounds in our standard packages.",
  vg_faq_4_q: "Can you film at my location?",
  vg_faq_4_a: "Yes, we film on-location anywhere or in our professional studio.",
  vg_faq_5_q: "Do you provide raw footage?",
  vg_faq_5_a: "Raw footage delivery is available as an add-on service.",
  vg_faq_6_q: "What's your booking process?",
  vg_faq_6_a: "Contact us to discuss your project, receive a quote, and schedule your shoot date.",
  vg_cta_title: "Ready to Grow?",
  vg_cta_btn: "Book Free Strategy Call",
  vg_cta_whatsapp: "Contact on WhatsApp",

  // ==================== PHOTOGRAPHY (ph) ====================
  ph_hero_title: "Commercial Photography",
  ph_hero_desc: "High-quality product, portrait, and commercial photography.",
  ph_why_title: "Why Choose Us",
  ph_stat_1_num: "+320%",
  ph_stat_1_label: "Visual Appeal Increase",
  ph_stat_2_num: "2.2x",
  ph_stat_2_label: "Click-Through Rate",
  ph_stat_3_num: "3 days",
  ph_stat_3_label: "Fast Delivery",
  ph_deliver_title: "What We Deliver",
  ph_deliver_1: "Product Photography — Clean, professional product shots.",
  ph_deliver_2: "Portrait Photography — Professional headshots and team photos.",
  ph_deliver_3: "Commercial Shoots — Brand and advertising photography.",
  ph_deliver_4: "Lifestyle Photography — Authentic brand moments.",
  ph_deliver_5: "E-commerce Photography — White background product images.",
  ph_deliver_6: "Photo Retouching — Professional post-processing.",
  ph_process_title: "Our Process",
  ph_process_1: "Concept",
  ph_process_2: "Shoot",
  ph_process_3: "Edit",
  ph_process_4: "Review",
  ph_process_5: "Deliver",
  ph_benefits_title: "Results & Benefits",
  ph_benefits_1: "Professional Image Quality",
  ph_benefits_2: "Consistent Brand Visuals",
  ph_benefits_3: "Higher Conversion Rates",
  ph_benefits_4: "Versatile Photo Library",
  ph_benefits_5: "Platform-Optimized Images",
  ph_benefits_6: "Fast Turnaround Time",
  ph_faq_title: "Frequently Asked Questions",
  ph_faq_1_q: "How many photos are included per shoot?",
  ph_faq_1_a: "Depending on the package, typically 20-50+ edited photos per session.",
  ph_faq_2_q: "Do you provide props and styling?",
  ph_faq_2_a: "Yes, we can arrange product styling and prop sourcing.",
  ph_faq_3_q: "What file formats do you deliver?",
  ph_faq_3_a: "High-resolution JPG, PNG, and RAW files as requested.",
  ph_faq_4_q: "Do you offer on-location shoots?",
  ph_faq_4_a: "Yes, we shoot on-location or in our professional studio.",
  ph_faq_5_q: "How long does photo editing take?",
  ph_faq_5_a: "Standard delivery is 3-5 business days after the shoot.",
  ph_faq_6_q: "Can you match a specific photography style?",
  ph_faq_6_a: "Absolutely. Share your vision and we'll match the style perfectly.",
  ph_cta_title: "Ready to Grow?",
  ph_cta_btn: "Book Free Strategy Call",
  ph_cta_whatsapp: "Contact on WhatsApp",

  // ==================== MEDIA BUYING (mb) ====================
  mb_hero_title: "Strategic Media Buying",
  mb_hero_desc: "Strategic media planning and buying across TV, digital, and out-of-home channels.",
  mb_why_title: "Why Choose Us",
  mb_stat_1_num: "-35%",
  mb_stat_1_label: "Media Cost Reduction",
  mb_stat_2_num: "5.2x",
  mb_stat_2_label: "Return on Investment",
  mb_stat_3_num: "+400%",
  mb_stat_3_label: "Reach Increase",
  mb_deliver_title: "What We Deliver",
  mb_deliver_1: "Media Planning — Strategic channel selection.",
  mb_deliver_2: "TV Buying — National and local TV placements.",
  mb_deliver_3: "Digital Buying — Programmatic and direct placements.",
  mb_deliver_4: "OOH Campaigns — Billboards and transit advertising.",
  mb_deliver_5: "Negotiation — Best rates and premium placements.",
  mb_deliver_6: "Performance Tracking — Cross-channel analytics.",
  mb_process_title: "Our Process",
  mb_process_1: "Research",
  mb_process_2: "Plan",
  mb_process_3: "Buy",
  mb_process_4: "Monitor",
  mb_process_5: "Optimize",
  mb_benefits_title: "Results & Benefits",
  mb_benefits_1: "Lower Media Costs",
  mb_benefits_2: "Wider Audience Reach",
  mb_benefits_3: "Better Placement Quality",
  mb_benefits_4: "Cross-Channel Synergy",
  mb_benefits_5: "Data-Driven Planning",
  mb_benefits_6: "Measurable ROI",
  mb_faq_title: "Frequently Asked Questions",
  mb_faq_1_q: "What media channels do you cover?",
  mb_faq_1_a: "TV, radio, digital, social, OOH, print, and programmatic advertising.",
  mb_faq_2_q: "How do you negotiate media rates?",
  mb_faq_2_a: "We leverage our network and volume to secure the best possible rates.",
  mb_faq_3_q: "Do you handle both planning and buying?",
  mb_faq_3_a: "Yes, we provide end-to-end media services from strategy to execution.",
  mb_faq_4_q: "Can you work with a specific budget?",
  mb_faq_4_a: "Absolutely. We optimize media plans to maximize results within your budget.",
  mb_faq_5_q: "How do you measure media performance?",
  mb_faq_5_a: "We track reach, frequency, GRPs, conversions, and custom KPIs.",
  mb_faq_6_q: "Do you provide media reports?",
  mb_faq_6_a: "Yes, we provide detailed campaign reports with actionable insights.",
  mb_cta_title: "Ready to Grow?",
  mb_cta_btn: "Book Free Strategy Call",
  mb_cta_whatsapp: "Contact on WhatsApp",

  // ==================== BRIEF PAGE — COMMON ====================
  brief_progress: "Progress",
  brief_continue: "Continue",
  brief_previous: "Previous",
  brief_review: "Review & Submit",
  brief_submit: "Submit Brief",
  brief_save: "Save Progress",
  brief_saved: "Progress saved",
  brief_success_title: "Brief Submitted!",
  brief_success_text: "Thank you for completing the brief. Our team will review your submission and get back to you within 24 hours.",
  brief_back_home: "Back to Home",
  brief_view_services: "View Services",
  brief_review_title: "Review Your Brief",
  brief_step_review_your_brief: "Review Your Brief",
  brief_desc_please_review_all_your_answers_before_submitting: "Please review all your answers before submitting.",
  brief_desc_please_review_all_your_answers_before_submitting_you_can_go_back_to_make_changes: "Please review all your answers before submitting. You can go back to make changes.",

  // ==================== BRIEF — SHARED LABELS ====================
  brief_label_business_name: "Business Name",
  brief_ph_eg_vivedfx: "e.g. VIVEDFX",
  brief_label_industry: "Industry",
  brief_label_target_audience: "Target Audience",
  brief_label_competitors: "Competitors",
  brief_label_additional_notes: "Additional Notes",
  brief_label_budget_range: "Budget Range",
  brief_label_deadline: "Deadline",

  // ==================== BRIEF — INDUSTRY OPTIONS ====================
  brief_select_select_your_industry: "Select your industry",
  brief_option_healthcare_medical: "Healthcare & Medical",
  brief_option_fitness_wellness: "Fitness & Wellness",
  brief_option_corporate_b2b: "Corporate & B2B",
  brief_option_ecommerce_retail: "E-Commerce & Retail",
  brief_option_real_estate: "Real Estate",
  brief_option_food_beverage: "Food & Beverage",
  brief_option_education: "Education",
  brief_option_technology_saas: "Technology & SaaS",
  brief_option_automotive: "Automotive",
  brief_option_fashion_beauty: "Fashion & Beauty",
  brief_option_hospitality_travel: "Hospitality & Travel",
  brief_option_other: "Other",
  brief_option_legal_financial: "Legal & Financial",

  // ==================== BRIEF — BUDGET OPTIONS ====================
  brief_select_select_your_budget_range: "Select your budget range",
  brief_option_under_500: "Under $500",
  brief_option_500_1000: "$500 - $1,000",
  brief_option_under_1000: "Under $1,000",
  brief_option_1000_3000: "$1,000 - $3,000",
  brief_option_3000_5000: "$3,000 - $5,000",
  brief_option_5000_10000: "$5,000 - $10,000",
  brief_option_10000: "$10,000+",
  brief_option_10000_20000: "$10,000 - $20,000",
  brief_option_20000: "$20,000+",
  brief_option_not_sure_yet: "Not sure yet",

  // ==================== BRIEF — MONTHLY BUDGET OPTIONS ====================
  brief_option_under_500month: "Under $500/month",
  brief_option_500_1000month: "$500 - $1,000/month",
  brief_option_1000_3000month: "$1,000 - $3,000/month",
  brief_option_3000_5000month: "$3,000 - $5,000/month",
  brief_option_5000_10000month: "$5,000 - $10,000/month",
  brief_option_5000month: "$5,000+/month",
  brief_option_10000month: "$10,000+/month",
  brief_option_under_1000month: "Under $1,000/month",

  // ==================== BRIEF — PLATFORM OPTIONS ====================
  brief_option_instagram: "Instagram",
  brief_option_facebook: "Facebook",
  brief_option_tiktok: "TikTok",
  brief_option_linkedin: "LinkedIn",
  brief_option_twitter_x: "Twitter / X",
  brief_option_youtube: "YouTube",
  brief_option_pinterest: "Pinterest",
  brief_option_snapchat: "Snapchat",
  brief_option_website: "Website",
  brief_option_email: "Email",

  // ==================== BRIEF — GOAL OPTIONS ====================
  brief_option_brand_awareness: "Brand Awareness",
  brief_option_lead_generation: "Lead Generation",
  brief_option_sales_conversions: "Sales & Conversions",
  brief_option_community_engagement: "Community Engagement",
  brief_option_website_traffic: "Website Traffic",
  brief_option_all_of_the_above: "All of the Above",
  brief_option_engagement: "Engagement",
  brief_option_app_installs: "App Installs",
  brief_option_conversions_sales: "Conversions / Sales",

  // ==================== BRIEF — CONTENT STYLE OPTIONS ====================
  brief_option_professional_polished: "Professional & Polished",
  brief_option_casual_friendly: "Casual & Friendly",
  brief_option_bold_edgy: "Bold & Edgy",
  brief_option_minimal_clean: "Minimal & Clean",
  brief_option_luxury_premium: "Luxury & Premium",

  // ==================== BRIEF — BRAND VOICE OPTIONS ====================
  brief_option_professional: "Professional",
  brief_option_friendly_casual: "Friendly & Casual",
  brief_option_authoritative: "Authoritative",
  brief_option_playful_fun: "Playful & Fun",

  // ==================== BRIEF — VISUAL STYLE OPTIONS ====================
  brief_option_modern_minimal: "Modern & Minimal",
  brief_option_classic_timeless: "Classic & Timeless",
  brief_option_bold_expressive: "Bold & Expressive",
  brief_option_tech_futuristic: "Tech & Futuristic",
  brief_option_bold_dynamic: "Bold & Dynamic",
  brief_option_corporate_professional: "Corporate & Professional",
  brief_option_creative_artistic: "Creative & Artistic",
  brief_option_tech_modern: "Tech & Modern",

  // ==================== BRIEF — EDITING STYLE OPTIONS ====================
  brief_option_cinematic_dramatic: "Cinematic & Dramatic",
  brief_option_clean_modern: "Clean & Modern",
  brief_option_fastpaced_energetic: "Fast-Paced & Energetic",
  brief_option_minimal_elegant: "Minimal & Elegant",
  brief_option_documentary_style: "Documentary Style",

  // ==================== BRIEF — VOLUME / QUANTITY OPTIONS ====================
  brief_select_select_volume: "Select volume",
  brief_option_12_posts_per_week: "1-2 posts per week",
  brief_option_34_posts_per_week: "3-4 posts per week",
  brief_option_daily_posts: "Daily posts",
  brief_option_multiple_posts_per_day: "Multiple posts per day",
  brief_option_not_sure_need_recommendation: "Not sure — need recommendation",
  brief_select_select_quantity: "Select quantity",
  brief_option_14_pieces_per_month: "1-4 pieces per month",
  brief_option_510_pieces_per_month: "5-10 pieces per month",
  brief_option_1020_pieces_per_month: "10-20 pieces per month",
  brief_option_20_pieces_per_month: "20+ pieces per month",
  brief_option_need_recommendation: "Need recommendation",

  // ==================== BRIEF — CONTENT TYPE OPTIONS ====================
  brief_option_social_media_posts: "Social Media Posts",
  brief_option_blog_articles: "Blog Articles",
  brief_option_email_marketing: "Email Marketing",
  brief_option_ad_copy: "Ad Copy",
  brief_option_website_copy: "Website Copy",
  brief_option_video_scripts: "Video Scripts",
  brief_option_presentations: "Presentations",
  brief_option_infographics: "Infographics",

  // ==================== BRIEF — VIDEO TYPE OPTIONS ====================
  brief_option_brand_company_profile: "Brand / Company Profile",
  brief_option_product_demo: "Product Demo",
  brief_option_social_media_video: "Social Media Video",
  brief_option_commercial_ad: "Commercial / Ad",
  brief_option_tutorial_howto: "Tutorial / How-To",
  brief_option_event_coverage: "Event Coverage",
  brief_option_testimonial_interview: "Testimonial / Interview",
  brief_option_motion_graphics_animation: "Motion Graphics / Animation",

  // ==================== BRIEF — DURATION OPTIONS ====================
  brief_select_select_target_duration: "Select target duration",
  brief_option_under_15_seconds_reeltiktok: "Under 15 seconds (Reel/TikTok)",
  brief_option_1530_seconds_adsocial: "15-30 seconds (Ad/Social)",
  brief_option_3060_seconds_promo: "30-60 seconds (Promo)",
  brief_option_12_minutes_profiledemo: "1-2 minutes (Profile/Demo)",
  brief_option_25_minutes_documentary_style: "2-5 minutes (Documentary style)",
  brief_option_5_minutes_long_form: "5+ minutes (Long form)",

  // ==================== BRIEF — SHOOT TYPE OPTIONS ====================
  brief_option_product_photography: "Product Photography",
  brief_option_corporate_headshots: "Corporate / Headshots",
  brief_option_lifestyle_brand: "Lifestyle / Brand",
  brief_option_real_estate_interior: "Real Estate / Interior",
  brief_option_fashion_apparel: "Fashion & Apparel",

  // ==================== BRIEF — INDOOR/OUTDOOR OPTIONS ====================
  brief_option_indoor: "Indoor",
  brief_option_outdoor: "Outdoor",
  brief_option_both: "Both",

  // ==================== BRIEF — WEBSITE PURPOSE OPTIONS ====================
  brief_option_brochure_info_site: "Brochure / Info Site",
  brief_option_ecommerce_online_store: "E-Commerce / Online Store",
  brief_option_booking_appointment: "Booking / Appointment",
  brief_option_portfolio_showcase: "Portfolio / Showcase",
  brief_option_saas_app_landing: "SaaS / App Landing",

  // ==================== BRIEF — PAGE OPTIONS ====================
  brief_option_home: "Home",
  brief_option_about_us: "About Us",
  brief_option_services: "Services",
  brief_option_portfolio_work: "Portfolio / Work",
  brief_option_blog: "Blog",
  brief_option_contact: "Contact",
  brief_option_pricing: "Pricing",
  brief_option_faq: "FAQ",
  brief_option_team: "Team",
  brief_option_testimonials: "Testimonials",
  brief_option_careers: "Careers",
  brief_option_custom_page: "Custom Page",

  // ==================== BRIEF — FEATURE OPTIONS ====================
  brief_option_contact_form: "Contact Form",
  brief_option_newsletter_signup: "Newsletter Signup",
  brief_option_live_chat: "Live Chat",
  brief_option_social_media_feed: "Social Media Feed",
  brief_option_analytics_dashboard: "Analytics Dashboard",
  brief_option_multilanguage: "Multi-Language",
  brief_option_custom_animations: "Custom Animations",
  brief_option_cms_content_management: "CMS (Content Management)",

  // ==================== BRIEF — BOOKING / PAYMENT OPTIONS ====================
  brief_option_yes_i_need_a_booking_system: "Yes, I need a booking system",
  brief_option_maybe_in_the_future: "Maybe in the future",
  brief_option_no: "No",
  brief_option_stripe: "Stripe",
  brief_option_paypal: "PayPal",
  brief_option_local_payment_gateway: "Local Payment Gateway",
  brief_option_not_needed: "Not needed",

  // ==================== BRIEF — LANGUAGE OPTIONS ====================
  brief_option_english_only: "English Only",
  brief_option_arabic_english: "Arabic + English",

  // ==================== BRIEF — SEO OPTIONS ====================
  brief_option_onpage_seo: "On-Page SEO",
  brief_option_technical_seo: "Technical SEO",
  brief_option_local_seo: "Local SEO",
  brief_option_schema_markup: "Schema Markup",
  brief_option_speed_optimization: "Speed Optimization",

  // ==================== BRIEF — HOSTING OPTIONS ====================
  brief_option_i_have_hosting: "I have hosting",
  brief_option_need_hosting_setup: "Need hosting setup",
  brief_option_not_sure: "Not sure",

  // ==================== BRIEF — PIXEL / TRACKING OPTIONS ====================
  brief_option_yes_installed: "Yes, installed",
  brief_option_yes_fully_set_up: "Yes, fully set up",
  brief_option_partial_setup: "Partial setup",
  brief_option_no_tracking_in_place: "No tracking in place",
  brief_option_yes_connected: "Yes, connected",

  // ==================== BRIEF — ANALYTICS OPTIONS ====================
  brief_option_ga4_installed: "GA4 installed",
  brief_option_old_analytics_ua: "Old Analytics (UA)",
  brief_option_no_analytics: "No analytics",

  // ==================== BRIEF — SCRIPT / ACTOR / DRONE / VO OPTIONS ====================
  brief_option_yes_i_have_a_script: "Yes, I have a script",
  brief_option_i_have_a_rough_idea: "I have a rough idea",
  brief_option_no_need_script_writing: "No, need script writing",
  brief_option_yes_provide_actors: "Yes, provide actors",
  brief_option_well_use_our_own_team: "We'll use our own team",
  brief_option_no_actors_needed: "No actors needed",
  brief_option_yes_aerial_footage_needed: "Yes, aerial footage needed",
  brief_option_no_drone_needed: "No drone needed",
  brief_option_yes_male_vo: "Yes, Male VO",
  brief_option_yes_female_vo: "Yes, Female VO",
  brief_option_no_voice_over: "No voice over",

  // ==================== BRIEF — AD PLATFORM OPTIONS ====================
  brief_option_google_ads: "Google Ads",
  brief_option_facebook_ads: "Facebook Ads",
  brief_option_instagram_ads: "Instagram Ads",
  brief_option_tiktok_ads: "TikTok Ads",
  brief_option_linkedin_ads: "LinkedIn Ads",
  brief_option_snapchat_ads: "Snapchat Ads",
  brief_option_none_starting_fresh: "None (Starting fresh)",

  // ==================== BRIEF — UPLOAD / HINT ====================
  brief_label_upload_reference_files: "Upload Reference Files",
  brief_upload_drop_files_here_or_click_to_upload: "Drop files here or click to upload",
  brief_hint_pdf_docx_jpg_png_ai_psd_zip_max_10_files: "PDF, DOCX, JPG, PNG, AI, PSD, ZIP \u2014 Max 10 files",
  brief_label_upload_existing_logo: "Upload Existing Logo",
  brief_upload_drop_your_existing_logo_here: "Drop your existing logo here",
  brief_hint_pdf_ai_psd_png_jpg_max_10_files: "PDF, AI, PSD, PNG, JPG \u2014 Max 10 files",
  brief_label_upload_brand_assets: "Upload Brand Assets",
  brief_upload_drop_brand_assets_here: "Drop brand assets here",
  brief_hint_guidelines_color_palettes_typography_patterns_max_10_files: "Guidelines, color palettes, typography, patterns \u2014 Max 10 files",
  brief_label_upload_files: "Upload Files",

  // ==================== BRIEF — SOCIAL MEDIA PAGE ====================
  brief_social_media_step_about_your_business: "About Your Business",
  brief_desc_lets_start_with_the_basics_so_we_understand_who_you_are: "Let's start with the basics so we understand who you are.",
  brief_ph_describe_your_ideal_customer_age_gender_interests_pain_points: "Describe your ideal customer \u2014 age, gender, interests, pain points...",
  brief_step_current_social_presence: "Current Social Presence",
  brief_desc_help_us_understand_where_you_currently_stand_on_social_media: "Help us understand where you currently stand on social media.",
  brief_label_current_social_media_accounts: "Current Social Media Accounts",
  brief_ph_list_your_social_media_profiles_and_follower_counts_eg_instagram_vivedfx_5k_followers: "List your social media profiles and follower counts (e.g. Instagram: @vivedfx \u2014 5K followers)",
  brief_label_biggest_challenges: "Biggest Challenges",
  brief_ph_what_are_you_struggling_with_most_on_social_media_eg_low_engagement_inconsistent_posting_no_strategy: "What are you struggling with most on social media? (e.g. low engagement, inconsistent posting, no strategy)",
  brief_ph_list_35_competitors_or_brands_you_admire_on_social_media: "List 3-5 competitors or brands you admire on social media",
  brief_step_goals_strategy: "Goals & Strategy",
  brief_desc_what_do_you_want_to_achieve_with_social_media_marketing: "What do you want to achieve with social media marketing?",
  brief_label_primary_goals: "Primary Goals",
  brief_label_platforms_required: "Platforms Required",
  brief_step_content_brand: "Content & Brand",
  brief_desc_how_should_your_brand_look_and_feel_on_social_media: "How should your brand look and feel on social media?",
  brief_label_preferred_content_style: "Preferred Content Style",
  brief_label_brand_personality: "Brand Personality",
  brief_ph_describe_your_brand_in_35_adjectives_eg_modern_bold_trustworthy_playful: "Describe your brand in 3-5 adjectives (e.g. modern, bold, trustworthy, playful)",
  brief_label_monthly_content_needed: "Monthly Content Needed",
  brief_step_budget_extras: "Budget & Extras",
  brief_desc_help_us_tailor_a_package_that_fits_your_needs_and_budget: "Help us tailor a package that fits your needs and budget.",
  brief_label_monthly_marketing_budget: "Monthly Marketing Budget",
  brief_ph_anything_else_youd_like_us_to_know_special_requirements_deadlines_references: "Anything else you'd like us to know? Special requirements, deadlines, references...",

  // ==================== BRIEF — BRANDING PAGE ====================
  brief_step_brand_foundation: "Brand Foundation",
  brief_desc_tell_us_the_story_behind_your_brand_what_drives_you_and_where_youre_headed: "Tell us the story behind your brand \u2014 what drives you and where you're headed.",
  brief_label_brand_story: "Brand Story",
  brief_ph_how_did_your_brand_start_whats_the_journey_behind_it: "How did your brand start? What's the journey behind it?",
  brief_label_mission: "Mission",
  brief_ph_what_is_your_companys_mission_why_do_you_exist: "What is your company's mission? Why do you exist?",
  brief_label_vision: "Vision",
  brief_ph_where_do_you_see_your_brand_in_510_years: "Where do you see your brand in 5-10 years?",
  brief_label_core_values: "Core Values",
  brief_ph_list_35_core_values_that_define_your_brand_eg_innovation_integrity_excellence: "List 3-5 core values that define your brand (e.g. innovation, integrity, excellence)",
  brief_step_target_audience: "Target Audience",
  brief_desc_who_are_you_trying_to_reach_the_more_specific_the_better: "Who are you trying to reach? The more specific, the better.",
  brief_ph_describe_your_ideal_customer_demographics_psychographics_behaviors_pain_points: "Describe your ideal customer \u2014 demographics, psychographics, behaviors, pain points",
  brief_step_visual_direction: "Visual Direction",
  brief_desc_what_should_your_brand_look_and_feel_like: "What should your brand look and feel like?",
  brief_label_preferred_style: "Preferred Style",
  brief_label_preferred_colors: "Preferred Colors",
  brief_ph_eg_dark_blue_gold_accents_or_describe_the_mood: "e.g. Dark blue, gold accents \u2014 or describe the mood",
  brief_label_colors_to_avoid: "Colors to Avoid",
  brief_ph_eg_no_bright_pink_no_neon_green: "e.g. No bright pink, no neon green",
  brief_step_logo_and_inspiration: "Logo & Inspiration",
  brief_desc_share_any_logo_ideas_or_brand_references_that_inspire_you: "Share any logo ideas or brand references that inspire you.",
  brief_label_logo_inspiration: "Logo Inspiration",
  brief_ph_describe_any_logo_ideas_you_have_style_symbols_layouts_or_share_links_to_references: "Describe any logo ideas you have \u2014 style, symbols, layouts, or share links to references",
  brief_label_brand_references: "Brand References",
  brief_ph_list_brands_whose_identity_you_admire_eg_apple_nike_aesop: "List brands whose identity you admire (e.g. Apple, Nike, Aesop)",
  brief_step_additional_details: "Additional Details",
  brief_desc_anything_else_that_will_help_us_create_the_perfect_brand_identity: "Anything else that will help us create the perfect brand identity.",
  brief_ph_eg_within_4_weeks_no_rush: "e.g. Within 4 weeks, No rush",
  brief_ph_anything_else_youd_like_us_to_know: "Anything else you'd like us to know?",

  // ==================== BRIEF — CONTENT CREATION PAGE ====================
  brief_step_content_type_and_audience: "Content Type & Audience",
  brief_desc_what_kind_of_content_do_you_need_and_who_is_it_for: "What kind of content do you need and who is it for?",
  brief_label_content_type: "Content Type",
  brief_label_platforms: "Platforms",
  brief_ph_who_are_you_creating_this_content_for: "Who are you creating this content for?",
  brief_step_brand_and_style: "Brand & Style",
  brief_desc_how_should_your_content_look_and_feel: "How should your content look and feel?",
  brief_label_brand_voice: "Brand Voice",
  brief_label_preferred_style: "Preferred Style",
  brief_ph_describe_the_visual_or_writing_style_you_prefer_eg_clean_with_bold_headlines_minimal_with_lots_of_white_space: "Describe the visual or writing style you prefer (e.g. clean with bold headlines, minimal with lots of white space)",
  brief_label_cta_style: "CTA Style",
  brief_ph_how_do_you_want_to_prompt_action_eg_soft_and_informative_direct_and_urgent_playful: "How do you want to prompt action? (e.g. soft and informative, direct and urgent, playful)",
  brief_step_topics_and_deliverables: "Topics & Deliverables",
  brief_desc_what_should_we_create_and_how_much: "What should we create and how much?",
  brief_label_monthly_deliverables: "Monthly Deliverables",
  brief_label_topics_themes: "Topics & Themes",
  brief_ph_what_topics_should_we_cover_list_themes_product_highlights_seasonal_content_ideas: "What topics should we cover? List themes, product highlights, seasonal content ideas...",
  brief_ph_list_competitors_whose_content_you_admire_what_do_you_like_about_their_content: "List competitors whose content you admire. What do you like about their content?",
  brief_label_references: "References",
  brief_ph_share_any_examples_of_content_you_love_links_screenshots_or_descriptions: "Share any examples of content you love \u2014 links, screenshots, or descriptions",
  brief_step_budget_and_extras: "Budget & Extras",
  brief_desc_final_details_to_get_started: "Final details to get started.",
  brief_ph_anything_else_special_requirements_brand_guidelines_content_calendar: "Anything else? Special requirements, brand guidelines, content calendar...",

  // ==================== BRIEF — VIDEOGRAPHY PAGE ====================
  brief_step_video_details: "Video Details",
  brief_desc_tell_us_about_the_video_you_need: "Tell us about the video you need.",
  brief_label_video_type: "Video Type",
  brief_label_objective: "Objective",
  brief_ph_what_should_this_video_achieve_eg_increase_brand_awareness_explain_our_service_drive_sales: "What should this video achieve? (e.g. increase brand awareness, explain our service, drive sales)",
  brief_label_duration: "Duration",
  brief_step_production_requirements: "Production Requirements",
  brief_desc_what_do_we_need_to_bring_to_the_shoot: "What do we need to bring to the shoot?",
  brief_label_shooting_location: "Shooting Location",
  brief_ph_eg_our_office_outdoor_location_studio_multiple_locations: "e.g. Our office, Outdoor location, Studio, Multiple locations",
  brief_label_script_available: "Script Available?",
  brief_label_actors_needed: "Actors Needed?",
  brief_label_drone_needed: "Drone Needed?",
  brief_label_voice_over_needed: "Voice Over Needed?",
  brief_step_editing_and_references: "Editing & References",
  brief_desc_how_should_the_final_video_look: "How should the final video look?",
  brief_label_editing_style: "Editing Style",
  brief_ph_paste_urls_of_videos_you_like_or_describe_the_look_and_feel_you_want: "Paste URLs of videos you like or describe the look and feel you want",
  brief_ph_eg_need_final_video_by_march_20: "e.g. Need final video by March 20",
  brief_desc_final_details_to_wrap_up_your_brief: "Final details to wrap up your brief.",

  // ==================== BRIEF — PHOTOGRAPHY PAGE ====================
  brief_step_shoot_details: "Shoot Details",
  brief_desc_tell_us_about_the_photoshoot_you_need: "Tell us about the photoshoot you need.",
  brief_label_business_type: "Business Type",
  brief_ph_eg_restaurant_gym_fashion_brand_corporate_office: "e.g. Restaurant, Gym, Fashion Brand, Corporate Office",
  brief_label_shoot_type: "Shoot Type",
  brief_label_products_or_services: "Products or Services",
  brief_ph_what_exactly_do_you_need_photographed_describe_the_products_services_or_scenes: "What exactly do you need photographed? Describe the products, services, or scenes.",
  brief_step_location_and_setup: "Location & Setup",
  brief_desc_where_and_how_will_the_shoot_take_place: "Where and how will the shoot take place?",
  brief_ph_eg_our_studio_clients_office_outdoor_park_restaurant: "e.g. Our studio, Client's office, Outdoor park, Restaurant",
  brief_label_indoor_or_outdoor: "Indoor or Outdoor?",
  brief_label_number_of_products: "Number of Products",
  brief_ph_eg_15_products_3_categories: "e.g. 15 products, 3 categories",
  brief_label_number_of_team_members: "Number of Team Members",
  brief_ph_eg_5_people_for_headshots: "e.g. 5 people for headshots",
  brief_step_style_and_delivery: "Style & Delivery",
  brief_desc_what_look_are_you_going_for: "What look are you going for?",
  brief_label_style_references: "Style References",
  brief_ph_describe_the_photography_style_you_want_or_paste_links_to_examples_you_love: "Describe the photography style you want, or paste links to examples you love",
  brief_label_delivery_date: "Delivery Date",
  brief_ph_eg_within_2_weeks_need_by_march_15: "e.g. Within 2 weeks, Need by March 15",
  brief_ph_anything_else_mood_color_grading_retouching_level_number_of_final_images: "Anything else? Mood, color grading, retouching level, number of final images...",

  // ==================== BRIEF — WEBSITE PAGE ====================
  brief_step_business_and_purpose: "Business & Purpose",
  brief_desc_tell_us_about_your_business_and_what_you_need_the_website_to_achieve: "Tell us about your business and what you need the website to achieve.",
  brief_label_business_information: "Business Information",
  brief_ph_business_name_what_you_do_location_years_in_business: "Business name, what you do, location, years in business...",
  brief_label_website_purpose: "Website Purpose",
  brief_ph_who_is_this_website_for_describe_your_ideal_visitor: "Who is this website for? Describe your ideal visitor.",
  brief_step_pages_and_features: "Pages & Features",
  brief_desc_what_pages_and_features_do_you_need: "What pages and features do you need?",
  brief_label_required_pages: "Required Pages",
  brief_label_required_features: "Required Features",
  brief_step_ecommerce_and_integrations: "E-Commerce & Integrations",
  brief_desc_do_you_need_online_selling_or_booking_capabilities: "Do you need online selling or booking capabilities?",
  brief_label_booking_system: "Booking System?",
  brief_label_payment_gateway: "Payment Gateway?",
  brief_label_languages: "Languages",
  brief_step_design_and_references: "Design & References",
  brief_desc_show_us_what_you_like_so_we_can_match_your_vision: "Show us what you like so we can match your vision.",
  brief_label_style_preference: "Style Preference",
  brief_label_reference_websites: "Reference Websites",
  brief_ph_paste_urls_of_websites_you_like_and_tell_us_what_you_like_about_them: "Paste URLs of websites you like and tell us what you like about them",
  brief_step_technical_and_seo: "Technical & SEO",
  brief_desc_tell_us_about_your_technical_requirements_and_seo_goals: "Tell us about your technical requirements and SEO goals.",
  brief_label_seo_requirements: "SEO Requirements",
  brief_label_domain: "Domain",
  brief_ph_eg_yourbusinesscom_or_need_help_choosing: "e.g. yourbusiness.com \u2014 or 'need help choosing'",
  brief_label_hosting: "Hosting",
  brief_step_budget_and_timeline: "Budget & Timeline",
  brief_desc_when_do_you_need_this_and_whats_your_budget: "When do you need this and what's your budget?",
  brief_ph_eg_launch_by_march_1st_asap_no_rush: "e.g. Launch by March 1st, ASAP, No rush",
  brief_ph_anything_else_special_features_integrations_existing_content: "Anything else? Special features, integrations, existing content...",

  // ==================== BRIEF — CONSULTATION PAGE ====================
  brief_step_about_your_business: "About Your Business",
  brief_desc_give_us_a_snapshot_of_your_business_and_where_it_stands_today: "Give us a snapshot of your business and where it stands today.",
  brief_label_current_situation: "Current Situation",
  brief_ph_describe_where_your_business_is_right_now_revenue_team_size_market_position_growth_stage: "Describe where your business is right now \u2014 revenue, team size, market position, growth stage...",
  brief_label_main_challenges: "Main Challenges",
  brief_ph_what_are_the_biggest_challenges_youre_facing_right_now: "What are the biggest challenges you're facing right now?",
  brief_step_goals_and_vision: "Goals & Vision",
  brief_desc_where_do_you_want_to_take_your_business: "Where do you want to take your business?",
  brief_label_goals: "Goals",
  brief_ph_what_do_you_want_to_achieve_shortterm_and_longterm_goals: "What do you want to achieve? Short-term and long-term goals.",
  brief_label_budget: "Budget",
  brief_label_timeline: "Timeline",
  brief_ph_eg_need_to_see_results_in_3_months_longterm_partnership: "e.g. Need to see results in 3 months, Long-term partnership",
  brief_ph_anything_else_youd_like_us_to_know_before_the_consultation: "Anything else you'd like us to know before the consultation?",

  // ==================== BRIEF — PERFORMANCE MARKETING PAGE ====================
  brief_step_business_overview: "Business Overview",
  brief_desc_tell_us_about_your_business_and_current_advertising_setup: "Tell us about your business and current advertising setup.",
  brief_ph_what_are_you_selling_describe_your_main_products_or_services: "What are you selling? Describe your main products or services.",
  brief_label_current_advertising_platforms: "Current Advertising Platforms",
  brief_step_budget_and_campaigns: "Budget & Campaigns",
  brief_desc_help_us_understand_your_budget_and_past_campaign_performance: "Help us understand your budget and past campaign performance.",
  brief_label_monthly_ad_budget: "Monthly Ad Budget",
  brief_label_previous_campaigns: "Previous Campaigns",
  brief_ph_have_you_run_ads_before_what_were_the_results_any_data_or_screenshots_you_can_share: "Have you run ads before? What were the results? Any data or screenshots you can share?",
  brief_label_landing_pages: "Landing Pages",
  brief_ph_do_you_have_existing_landing_pages_paste_urls_or_describe_them: "Do you have existing landing pages? Paste URLs or describe them.",
  brief_step_targeting: "Targeting",
  brief_desc_who_are_you_trying_to_reach_with_your_ads: "Who are you trying to reach with your ads?",
  brief_label_target_locations: "Target Locations",
  brief_ph_eg_usa_nationwide_nyc_metro_area_worldwide: "e.g. USA nationwide, NYC metro area, Worldwide",
  brief_ph_list_competitors_who_are_also_running_ads_any_insights_on_their_approach: "List competitors who are also running ads. Any insights on their approach?",
  brief_step_tracking_and_technical: "Tracking & Technical",
  brief_desc_tell_us_about_your_current_tracking_setup: "Tell us about your current tracking setup.",
  brief_label_existing_pixel: "Existing Pixel?",
  brief_label_existing_conversion_tracking: "Existing Conversion Tracking?",
  brief_label_main_objective: "Main Objective",
  brief_step_kpis_and_extras: "KPIs & Extras",
  brief_desc_what_metrics_matter_most_to_you: "What metrics matter most to you?",
  brief_label_key_performance_indicators_kpis: "Key Performance Indicators (KPIs)",
  brief_ph_what_metrics_do_you_want_us_to_optimize_for_eg_cost_per_lead_roas_ctr_cpa: "What metrics do you want us to optimize for? (e.g. cost per lead, ROAS, CTR, CPA)",
  brief_ph_anything_else_past_experiences_specific_requirements_references: "Anything else? Past experiences, specific requirements, references...",

  // ==================== BRIEF — MARKETING STRATEGY PAGE ====================
  brief_desc_give_us_a_complete_picture_of_your_business_and_where_it_stands_today: "Give us a complete picture of your business and where it stands today.",
  brief_label_business_overview: "Business Overview",
  brief_ph_tell_us_about_your_business_what_you_do_who_you_serve_how_long_youve_been_operating_size_of_team: "Tell us about your business \u2014 what you do, who you serve, how long you've been operating, size of team...",
  brief_label_current_marketing_activities: "Current Marketing Activities",
  brief_ph_what_marketing_are_you_currently_doing_eg_social_media_google_ads_content_marketing_print_events: "What marketing are you currently doing? (e.g. social media, Google Ads, content marketing, print, events)",
  brief_step_goals_and_challenges: "Goals & Challenges",
  brief_desc_where_do_you_want_to_go_and_whats_holding_you_back: "Where do you want to go and what's holding you back?",
  brief_label_revenue_goals: "Revenue Goals",
  brief_ph_what_are_your_revenue_targets_eg_100kmonth_2x_revenue_in_12_months: "What are your revenue targets? (e.g. $100K/month, 2x revenue in 12 months)",
  brief_ph_what_are_the_biggest_obstacles_to_your_growth_eg_low_brand_awareness_not_enough_leads_poor_conversion_rates: "What are the biggest obstacles to your growth? (e.g. low brand awareness, not enough leads, poor conversion rates)",
  brief_label_growth_goals: "Growth Goals",
  brief_ph_where_do_you_want_to_be_in_612_months_what_does_success_look_like: "Where do you want to be in 6-12 months? What does success look like?",
  brief_step_audience_and_competition: "Audience & Competition",
  brief_desc_who_are_you_targeting_and_who_are_you_up_against: "Who are you targeting and who are you up against?",
  brief_ph_describe_your_ideal_customer_in_detail_demographics_psychographics_behaviors: "Describe your ideal customer in detail \u2014 demographics, psychographics, behaviors",
  brief_ph_list_35_main_competitors_what_are_they_doing_well_where_do_they_fall_short: "List 3-5 main competitors. What are they doing well? Where do they fall short?",
  brief_label_unique_selling_proposition: "Unique Selling Proposition",
  brief_ph_what_makes_you_different_from_competitors_why_should_customers_choose_you: "What makes you different from competitors? Why should customers choose you?",
  brief_step_budget_and_kpis: "Budget & KPIs",
  brief_desc_how_much_are_you_investing_and_what_metrics_matter: "How much are you investing and what metrics matter?",
  brief_ph_what_metrics_will_you_judge_success_by_eg_leads_per_month_conversion_rate_revenue_growth_social_engagement: "What metrics will you judge success by? (e.g. leads per month, conversion rate, revenue growth, social engagement)",
  brief_ph_anything_else_past_experiences_specific_requirements_timeline_expectations: "Anything else? Past experiences, specific requirements, timeline expectations...",

  // ==================== BRIEF — SEO PAGE ====================
  brief_step_website_and_business: "Website & Business",
  brief_desc_tell_us_about_your_website_and_business_so_we_can_assess_your_seo_needs: "Tell us about your website and business so we can assess your SEO needs.",
  brief_label_website_url: "Website URL",
  brief_ph_httpsyourwebsitecom: "https://yourwebsite.com",
  brief_label_business_category: "Business Category",
  brief_select_select_your_category: "Select your category",
  brief_label_target_keywords: "Target Keywords",
  brief_ph_list_keywords_you_want_to_rank_for_eg_digital_marketing_agency_dubai_best_fitness_trainer_near_me: "List keywords you want to rank for (e.g. 'digital marketing agency Dubai', 'best fitness trainer near me')",
  brief_ph_eg_dubai_uae_worldwide: "e.g. Dubai, UAE, Worldwide",
  brief_step_current_seo_status: "Current SEO Status",
  brief_desc_what_seo_work_have_you_already_done: "What SEO work have you already done?",
  brief_label_existing_seo_work: "Existing SEO Work",
  brief_ph_describe_any_seo_work_done_before_onpage_offpage_link_building_content_creation: "Describe any SEO work done before \u2014 on-page, off-page, link building, content creation...",
  brief_label_google_search_console: "Google Search Console",
  brief_label_google_analytics: "Google Analytics",
  brief_step_goals_and_priorities: "Goals & Priorities",
  brief_desc_what_do_you_want_to_achieve_with_seo: "What do you want to achieve with SEO?",
  brief_label_monthly_goals: "Monthly Goals",
  brief_ph_what_are_your_monthly_trafficranking_goals_eg_rank_on_page_1_for_5_keywords_10k_monthly_visitors: "What are your monthly traffic/ranking goals? (e.g. rank on page 1 for 5 keywords, 10K monthly visitors)",
  brief_label_priority_pages: "Priority Pages",
  brief_ph_which_pages_are_most_important_to_rank_eg_homepage_service_pages_blog_posts: "Which pages are most important to rank? (e.g. homepage, service pages, blog posts)",
  brief_ph_list_35_competitors_who_rank_well_for_your_target_keywords: "List 3-5 competitors who rank well for your target keywords",

  // Service page stat wrappers (no text content)
  bi_stat_1: "",
  bi_stat_2: "",
  bi_stat_3: "",
  gd_stat_1: "",
  gd_stat_2: "",
  gd_stat_3: "",
  mb_stat_1: "",
  mb_stat_2: "",
  mb_stat_3: "",
  pa_stat_1: "",
  pa_stat_2: "",
  pa_stat_3: "",
  ph_stat_1: "",
  ph_stat_2: "",
  ph_stat_3: "",
  sm_stat_1: "",
  sm_stat_2: "",
  sm_stat_3: "",
  ve_stat_1: "",
  ve_stat_2: "",
  ve_stat_3: "",
  vg_stat_1: "",
  vg_stat_2: "",
  vg_stat_3: "",
  wd_stat_1: "",
  wd_stat_2: "",
  wd_stat_3: ""
};
