// VIVEDFX Arabic Translations
// Auto-generated language file

window.AR = {
  // Navigation
  nav_services: "خدماتنا",
  nav_portfolio: "أعمالنا",
  nav_industries: "القطاعات",
  nav_process: "منهجيتنا",
  nav_clients: "عملاؤنا",
  nav_book_call: "احجز مكالمة",

  // Hero Section
  hero_label: "وكالة تسويق",
  hero_title_1: "نبني",
  hero_title_2: "علامات تجارية",
  hero_title_3: "يحبها الجميع",
  hero_sub: "نحوّل الأفكار إلى اهتمام وثقة ونمو עסקי من خلال استراتيجية إبداعية وتسويق أداءي.",
  hero_cta_1: "احجز مكالمة استراتيجية",
  hero_cta_2: "شاهد أعمالنا",
  hero_stat_1_num: "+150",
  hero_stat_1_label: "عميل حول العالم",
  hero_stat_2_num: "98%",
  hero_stat_2_label: "معدل الاحتفاظ",
  hero_stat_3_num: "3.8x",
  hero_stat_3_label: "متوسط العائد",

  // Marquee
  marquee_1: "وسائل التواصل",
  marquee_2: "الهوية البصرية",
  marquee_3: "المونتاج",
  marquee_4: "الإعلانات",
  marquee_5: "التصميم",
  marquee_6: "تصميم المواقع",
  marquee_7: "التصوير المرئي",
  marquee_8: "التصوير",
  marquee_9: "شراء الإعلانات",

  // Services Section
  services_label: "ما نقدمه",
  services_title: "خدمات تحقق نتائج",
  services_title_accent: "",
  services_desc: "كل ما تحتاجه علامتك التجارية للنمو والتحويل والتفوق.",

  // Portfolio Section
  portfolio_label: "أعمالنا",
  portfolio_title: "نتائج حققناها",
  portfolio_title_accent: "",
  portfolio_all: "الكل",
  portfolio_medical: "طبي",
  portfolio_fitness: "لياقة",
  portfolio_corporate: "مؤسسي",

  // Stats Section
  stats_label: "متوسط نتائج العملاء",
  stats_title: "النتائج",
  stats_title_accent: "التي حققناها",

  // Industries Section
  ind_label: "قطاعات نخدمها",
  ind_title: "قطاعات متخصصة",
  ind_title_accent: "",
  ind_1: "أطباء وعيادات",
  ind_2: "صالات اللياقة والرياضية",
  ind_3: "شركات هندسية",
  ind_4: "شركات مؤسسية",
  ind_5: "مطاعم والأغذية والمشروبات",
  ind_6: "معلمون ومراكز تعليمية",

  // Process Section
  process_label: "كيف نعمل",
  process_title: "منهجيتنا",
  process_title_accent: "",
  process_1_title: "الاكتشاف",
  process_1_desc: "غوص عميق في عملك وcompetitors وجمهور المستهدف لفهم ما يميزك حقًا.",
  process_2_title: "الاستراتيجية",
  process_2_desc: "خارطة طريق مخصصة حول أهدافك — أي القنوات وأي المحتوى وأي الميزانية ستحقق أقصى نتائج.",
  process_3_title: "الإنتاج",
  process_3_desc: "تنفيذ إبداعي عالمي — محتوى وتصميم وفيديو ونصوص — كلها منتجة بأعلى المعايير من فريقنا الداخلي.",
  process_4_title: "الإطلاق",
  process_4_desc: "نشر دقيق عبر المنصات — كل منشور وإعلان ومحتوى يُنشر في الوقت المثلي لأقصى تأثير.",

  // Testimonials Section
  test_label: "عملاؤنا يحبوننا",
  test_title: "ما يقوله عملاؤنا",
  test_title_accent: "",
  test_1_text: "vivedfx حوّلت بالكامل حضور عيادتنا عبر الإنترنت. في 4 أشهر انتقلنا من شبه عدم تفاعل اجتماعي إلى أكثر من 40,000 ظهور شهريًا. حجوزات المرضى الجدد ارتفعت 3 مرات وأخيرًا تبدو علامتنا التجارية احترافية كالخدمة التي نقدمها.",
  test_1_name: "د. أحمد حسن",
  test_1_role: "مؤسس، عيادة ميدي كير بلس",
  test_2_text: "اشتراكات صالتنا الرياضية تضاعفت في 6 أشهر بعد أن أطلقت vivedfx حملة إعادة التسمية والإعلانات. العمل الإبداعي رائع — مجتمعنا يحب المحتوى وcompetitors يراقبوننا بوضوح الآن. أفضل استثمار قمنا به.",
  test_2_name: "سارة ميتشل",
  test_2_role: "مالكة، أيرون إيدج فيتنس",
  test_3_text: "كمكتب هندسي، كنا نعاني من التواصل بما نفعله بطريقة مقنعة. بنت لنا vivedfx علامة تجارية نفخر بها حقًا وموقعًا إلكترونيًا يُولّد عملاء محتملين حقيقيين. الإيرادات من القنوات الرقمية ارتفعت أكثر من 200% مقارنة بالعام السابق.",
  test_3_name: "جيمس أوكونكو",
  test_3_role: "الرئيس التنفيذي، بيلد كور هندسة",

  // CTA Section
  cta_title: "جاهز لتنمية أعمالك؟",
  cta_title_accent: "",
  cta_sub: "احجز مكالمة استراتيجية مجانية اليوم. لا ضغط ولا التزام — فقط خطة واضحة لنمو علامتك التجارية.",
  cta_btn: "احجز استشارة مجانية",

  // Footer
  footer_desc: "نبني علامات تجارية يحبها الجميع. وكالة تسويق متميزة تخدم الشركات التي تطلب النتائج.",
  footer_services: "خدماتنا",
  footer_industries: "القطاعات",
  footer_start_project: "ابدأ مشروعك",
  footer_rights: "\u00a9 2026 VIVEDFX. جميع الحقوق محفوظة. مبني للعلامات التجارية الجادة.",
  footer_privacy: "سياسة الخصوصية",
  footer_terms: "شروط الخدمة",

  // Common Buttons
  back_to_home: "الرئيسية",
  view_full_details: "عرض التفاصيل",
  prev_service: "الخدمة السابقة",
  next_service: "الخدمة التالية",
  book_free_call: "احجز مكالمة استراتيجية مجانية",
  contact_whatsapp: "تواصل عبر واتساب",
  svc_start_brief: "ابدأ البريف",

  // Service Overview Cards
  sv_1_title: "إدارة وسائل التواصل الاجتماعي",
  sv_1_desc: "إنشاء محتوى استراتيجي وإدارة مجتمعات وتحليلات تبني جماهير وتزيد التفاعل.",
  sv_2_title: "الهوية البصرية",
  sv_2_desc: "أنظمة بصرية متكاملة — شعارات وألوان وخطوط وأدلة علامة تجارية.",
  sv_3_title: "المونتاج",
  sv_3_desc: "ريلز سينمائية وأفلام علامة تجارية ومراجع ومقاطع قصيرة محسّنة لأقصى انتشار.",
  sv_4_title: "التصميم الجرافيكي",
  sv_4_desc: "تصاميم تجذب الانتباه — إعلانات وبانرات ومطبوعات مصممة للتحويل.",
  sv_5_title: "الإعلانات المدفوعة",
  sv_5_desc: "حملات إعلانية على Meta وGoogle وTikTok مصممة لأقصى عائد.",
  sv_6_title: "تصميم المواقع",
  sv_6_desc: "مواقع عالية التحويل وسريعة وجميلة مبنية لتحويل الزوار إلى عملاء.",
  sv_7_title: "التصوير المرئي السينمائي",
  sv_7_desc: "إنتاج فيديو احترافي — تصوير مؤسسي وفعاليات ومقاطع منتجات.",
  sv_8_title: "التصوير الفوتوغرافي التجاري",
  sv_8_desc: "تصوير منتجات وبورتريه وتصوير تجاري عالي الجودة.",
  sv_9_title: "شراء الإعلانات الاستراتيجي",
  sv_9_desc: "التخطيط والشراء الاستراتيجي للإعلانات عبر التلفزيون والرقمي.",

  // ==================== SERVICES PAGE ====================
  svc_page_title: "كل ما تحتاجه علامتك التجارية للنمو",
  svc_page_desc: "من الاستراتيجية إلى الإنتاج، نقدم خدمات إبداعية وتسويقية شاملة تبني العلامات التجارية وتجلب العملاء وتُوسّع الأعمال عبر كل قناة.",
  svc_cta_title: "جاهز للبدء؟",
  svc_cta_desc: "احجز مكالمة استراتيجية مجانية وسنريك بالضبط كيف سنموّ أعمالك عبر كل قناة.",
  svc_cta_btn: "احجز استشارة مجانية",

  // ==================== PORTFOLIO PAGE ====================
  port_page_title: "أعمالنا",
  port_page_desc: "تصفح أعمالنا عبر القطاعات.",

  // ==================== SOCIAL MEDIA (sm) ====================
  sm_hero_title: "إدارة وسائل التواصل الاجتماعي",
  sm_hero_desc: "إنشاء محتوى استراتيجي وإدارة مجتمعات وتحليلات تبني جماهير وتزيد التفاعل.",
  sm_why_title: "لماذا تختارنا",
  sm_stat_1_num: "+420%",
  sm_stat_1_label: "زيادة التفاعل",
  sm_stat_2_num: "3.8x",
  sm_stat_2_label: "نمو المتابعين",
  sm_stat_3_num: "90 يوم",
  sm_stat_3_label: "لنتائج ملموسة",
  sm_deliver_title: "ما نقدمه",
  sm_deliver_1: "استراتيجية المحتوى — تقويم محتوى شهري مخصص لصوت علامتك التجارية.",
  sm_deliver_2: "نشر يومي — نشر منتظم عبر جميع المنصات.",
  sm_deliver_3: "إدارة المجتمعات — الرد على التعليقات والرسائل.",
  sm_deliver_4: "تحليلات شهرية — رؤى أداء مفصلة.",
  sm_deliver_5: "إنشاء محتوى بصري — تصاميم وكاروسيل تجذب الانتباه.",
  sm_deliver_6: "بحث الهاشتاغات — مجموعات هاشتاغات استراتيجية لأقصى انتشار.",
  sm_process_title: "كيف نعمل",
  sm_process_1: "التدقيق",
  sm_process_2: "الاستراتيجية",
  sm_process_3: "الإنشاء",
  sm_process_4: "النشر",
  sm_process_5: "التحسين",
  sm_benefits_title: "النتائج والمزايا",
  sm_benefits_1: "متابعين أكثر تفاعلًا",
  sm_benefits_2: "سلطة علامة تجارية أقوى",
  sm_benefits_3: "زيارات موقع أعلى",
  sm_benefits_4: "علاقات أفضل بالعملاء",
  sm_benefits_5: "حرية الوقت",
  sm_benefits_6: "نمو قائم على البيانات",
  sm_faq_title: "الأسئلة الشائعة",
  sm_faq_1_q: "ما هي المنصات التي تديرونها؟",
  sm_faq_1_a: "ندير Instagram وFacebook وTikTok وLinkedIn وTwitter/X وPinterest وYouTube.",
  sm_faq_2_q: "كم منشور تنشئون شهريًا؟",
  sm_faq_2_a: "حسب خطتك، ننشئ 15-30+ منشور شهريًا.",
  sm_faq_3_q: "هل تديرون الإعلانات المدفوعة أيضًا؟",
  sm_faq_3_a: "نعم، نقدم إدارة الإعلانات المدفوعة كخدمة إضافية.",
  sm_faq_4_q: "متى سأرى النتائج؟",
  sm_faq_4_a: "معظم العملاء يرون زيادة التفاعل خلال 2-4 أسابيع.",
  sm_faq_5_q: "هل يمكنني الموافقة على المحتوى قبل النشر؟",
  sm_faq_5_a: "بالطبع. نرسل تقويمات المحتوى لموافقتك قبل النشر.",
  sm_faq_6_q: "هل تكتبون التعليقات والهاشتاغات أيضًا؟",
  sm_faq_6_a: "نعم، كل منشور يتضمن تعليقات احترافية وهاشتاغات بحث استراتيجي.",
  sm_cta_title: "جاهز للنمو؟",
  sm_cta_btn: "احجز مكالمة استراتيجية مجانية",
  sm_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== BRAND IDENTITY (bi) ====================
  bi_hero_title: "الهوية البصرية",
  bi_hero_desc: "أنظمة بصرية متكاملة — شعارات وألوان وخطوط وأدلة علامة تجارية.",
  bi_why_title: "لماذا تختارنا",
  bi_stat_1_num: "+380%",
  bi_stat_1_label: "التعرف على العلامة",
  bi_stat_2_num: "2.5x",
  bi_stat_2_label: "زيادة ثقة العملاء",
  bi_stat_3_num: "30 يوم",
  bi_stat_3_label: "تسليم الهوية كاملة",
  bi_deliver_title: "ما نقدمه",
  bi_deliver_1: "تصميم الشعار — إصدارات رئيسية وثانوية وأيقونة.",
  bi_deliver_2: "نظام الألوان — ألوان رئيسية وثانوية ومتعادلة.",
  bi_deliver_3: "الطباعة — مجموعة خطوط منظمة بقواعد التسلسل الهرمي.",
  bi_deliver_4: "أدلة العلامة — وثيقة اتساق شاملة.",
  bi_deliver_5: "بطاقات أعمال ومطبوعات — مواد مطبوعة متكاملة.",
  bi_deliver_6: "أنماط ورسومات العلامة — عناصر بصرية لجميع نقاط التماس.",
  bi_process_title: "كيف نعمل",
  bi_process_1: "البحث",
  bi_process_2: "لوحة المزاج",
  bi_process_3: "التصميم",
  bi_process_4: "التحسين",
  bi_process_5: "التسليم",
  bi_benefits_title: "النتائج والمزايا",
  bi_benefits_1: "تعرف فوري على العلامة",
  bi_benefits_2: "تموضع مهني في السوق",
  bi_benefits_3: "هوية بصرية متسقة",
  bi_benefits_4: "ثقة عملاء متزايدة",
  bi_benefits_5: "ميزة تنافسية",
  bi_benefits_6: "قيمة علامة طويلة الأمد",
  bi_faq_title: "الأسئلة الشائعة",
  bi_faq_1_q: "كم تستغرق الهوية البصرية؟",
  bi_faq_1_a: "عادة 2-4 أسابيع من الاكتشاف إلى التسليم النهائي.",
  bi_faq_2_q: "هل أمتلك التصاميم النهائية؟",
  bi_faq_2_a: "نعم، تتلقى ملكية كاملة لجميع الملفات والمستندات المصدرية.",
  bi_faq_3_q: "كم عدد المراجعات المضمنة؟",
  bi_faq_3_a: "نقدم حتى 3 جولات من المراجعات في كل مشروع.",
  bi_faq_4_q: "ما هي صيغ الملفات التي أتلقاها؟",
  bi_faq_4_a: "AI وEPS وPDF وPNG وJPG وSVG بجميع تنسيقات الألوان.",
  bi_faq_5_q: "هل يمكنكم العمل مع علامتي الحالية؟",
  bi_faq_5_a: "نعم، يمكننا تحديث وتحسين هويتك البصرية الحالية.",
  bi_faq_6_q: "هل تنشئون أدلة العلامة؟",
  bi_faq_6_a: "نعم، كل مشروع يتضمن وثيقة أداة علامة شاملة.",
  bi_cta_title: "جاهز للنمو؟",
  bi_cta_btn: "احجز مكالمة استراتيجية مجانية",
  bi_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== VIDEO EDITING (ve) ====================
  ve_hero_title: "المونتاج",
  ve_hero_desc: "ريلز سينمائية وأفلام علامة تجارية ومراجع ومقاطع قصيرة محسّنة لأقصى انتشار.",
  ve_why_title: "لماذا تختارنا",
  ve_stat_1_num: "+500%",
  ve_stat_1_label: "زيادة المشاهدات",
  ve_stat_2_num: "4.2x",
  ve_stat_2_label: "نمو وقت المشاهدة",
  ve_stat_3_num: "7 أيام",
  ve_stat_3_label: "سرعة في التسليم",
  ve_deliver_title: "ما نقدمه",
  ve_deliver_1: "ريلز ومقاطع قصيرة — محتوى عمودي يجذب الانتباه.",
  ve_deliver_2: "أفلام علامة تجارية — سرد سينمائي لعلامتك التجارية.",
  ve_deliver_3: "مراجعات — فيديوهات احترافية لآراء العملاء.",
  ve_deliver_4: "رسوم متحركة — تراكبات وانتقالات متحركة.",
  ve_deliver_5: "تصحيح الألوان — تصحيح ألوان سينمائي احترافي.",
  ve_deliver_6: "تصميم الصوت — اختيار موسيقى ومix صوتي.",
  ve_process_title: "كيف نعمل",
  ve_process_1: "البريف",
  ve_process_2: "المونتاج",
  ve_process_3: "المراجعة",
  ve_process_4: "التحسين",
  ve_process_5: "التسليم",
  ve_benefits_title: "النتائج والمزايا",
  ve_benefits_1: "معدلات تفاعل أعلى",
  ve_benefits_2: "صورة علامة تجارية احترافية",
  ve_benefits_3: "زيادة وقت المشاهدة",
  ve_benefits_4: "أداء محتوى أفضل",
  ve_benefits_5: "توفير الوقت",
  ve_benefits_6: "محتوى محسّن لكل منصة",
  ve_faq_title: "الأسئلة الشائعة",
  ve_faq_1_q: "ما هي صيغ الفيديو التي تسلمونها؟",
  ve_faq_1_a: "نسلم MP4 وMOV وتنسيقات مخصصة لكل منصة.",
  ve_faq_2_q: "كم يستغرق المونتاج العادي؟",
  ve_faq_2_a: "المونتاج العادي يستغرق 3-5 أيام عمل. التسليم السريع متاح.",
  ve_faq_3_q: "هل تقدمون مراجعات؟",
  ve_faq_3_a: "نعم، نقدم حتى 3 جولات من المراجعات مع كل مشروع.",
  ve_faq_4_q: "هل يمكنكم مطابقة نمط علامتي التجارية؟",
  ve_faq_4_a: "بالطبع. نكيّف أسلوب المونتاج ليتوافق مع أدلتك التجارية.",
  ve_faq_5_q: "هل تتعاملون مع التعليقات الصوتية؟",
  ve_faq_5_a: "نعم، يمكننا ترتيب خدمات تعليق صوتي احترافي بلغات متعددة.",
  ve_faq_6_q: "ماذا لو احتجت إلى مونتاج مستمر؟",
  ve_faq_6_a: "نقدم حزم شهرية للحصول على محتوى فيديو مستمر.",
  ve_cta_title: "جاهز للنمو؟",
  ve_cta_btn: "احجز مكالمة استراتيجية مجانية",
  ve_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== GRAPHIC DESIGN (gd) ====================
  gd_hero_title: "التصميم الجرافيكي",
  gd_hero_desc: "تصاميم تجذب الانتباه — إعلانات وبانرات ومطبوعات مصممة للتحويل.",
  gd_why_title: "لماذا تختارنا",
  gd_stat_1_num: "+350%",
  gd_stat_1_label: "زيادة التحويل",
  gd_stat_2_num: "2.8x",
  gd_stat_2_label: "معدل النقر",
  gd_stat_3_num: "48 ساعة",
  gd_stat_3_label: "تسليم سريع",
  gd_deliver_title: "ما نقدمه",
  gd_deliver_1: "تصميم منشورات التواصل — منشورات وقصص وغلاف.",
  gd_deliver_2: "إعلانات — بانرات وdisplay ads.",
  gd_deliver_3: "تصميم مطبوعات — كتيبات ونقوط وملصقات.",
  gd_deliver_4: "تصميم التغليف — تغليف وتسميات المنتجات.",
  gd_deliver_5: "تصميم العروض — عروض تقديمية احترافية.",
  gd_deliver_6: "مجموعات أيقونات — مكتبات أيقونات مخصصة.",
  gd_process_title: "كيف نعمل",
  gd_process_1: "المفهوم",
  gd_process_2: "التصميم",
  gd_process_3: "المراجعة",
  gd_process_4: "التحسين",
  gd_process_5: "التسليم",
  gd_benefits_title: "النتائج والمزايا",
  gd_benefits_1: "هوية بصرية احترافية",
  gd_benefits_2: "معدلات تحويل أعلى",
  gd_benefits_3: "عرض علامة تجارية متسق",
  gd_benefits_4: "إنتاج محتوى أسرع",
  gd_benefits_5: "تسليم بعدة صيغ",
  gd_benefits_6: "أنظمة تصميم قابلة للتوسيع",
  gd_faq_title: "الأسئلة الشائعة",
  gd_faq_1_q: "ما هي صيغ التصميم التي تقدمونها؟",
  gd_faq_1_a: "PSD وAI وPDF وPNG وJPG وملفات المصدر حسب الطلب.",
  gd_faq_2_q: "كم مفهومًا تقدمونه؟",
  gd_faq_2_a: "نقدم عادة 2-3 مفاهيم لكل مشروع لاختيارك.",
  gd_faq_3_q: "هل تقدمون خدمات تصميم سريعة؟",
  gd_faq_3_a: "نعم، نقدم تسليمًا مسرّعًا للمشاريع العاجلة برسوم إضافية.",
  gd_faq_4_q: "هل يمكنكم مطابقة أدلتك التجارية الحالية؟",
  gd_faq_4_a: "بالطبع. نتأكد أن جميع التصاميم تتوافق مع معايير علامتك التجارية.",
  gd_faq_5_q: "هل تقدمون ملفات جاهزة للطباعة؟",
  gd_faq_5_a: "نعم، جميع التصاميم المطبوعة تتضمن ملفات CMYK مع فراغ وعلامات القص.",
  gd_faq_6_q: "ماذا لو احتجت إلى مراجعات تصميم لاحقًا؟",
  gd_faq_6_a: "نقدم حزم مرونة للمراجعات لاحتياجات التصميم المستمرة.",
  gd_cta_title: "جاهز للنمو؟",
  gd_cta_btn: "احجز مكالمة استراتيجية مجانية",
  gd_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== PAID ADVERTISING (pa) ====================
  pa_hero_title: "الإعلانات المدفوعة",
  pa_hero_desc: "حملات إعلانية على Meta وGoogle وTikTok مصممة لأقصى عائد.",
  pa_why_title: "لماذا تختارنا",
  pa_stat_1_num: "4.5x",
  pa_stat_1_label: "متوسط العائد على الإنفاق",
  pa_stat_2_num: "-40%",
  pa_stat_2_label: "تكلفة العميل",
  pa_stat_3_num: "+280%",
  pa_stat_3_label: "نمو الإيرادات",
  pa_deliver_title: "ما نقدمه",
  pa_deliver_1: "استراتيجية الحملة — خطط إعلانية شاملة.",
  pa_deliver_2: "إنشاء الإعلانات — نصوص ومرئيات وفيديو.",
  pa_deliver_3: "استهداف الجمهور — استهداف دقيق حسب الديموغرافيا.",
  pa_deliver_4: "اختبار A/B — تحسين مستمر للإعلانات.",
  pa_deliver_5: "تقارير الأداء — تحليلات وأفكار أسبوعية.",
  pa_deliver_6: "إعادة الاستهداف — حملات استرداد للزوار المفقودين.",
  pa_process_title: "كيف نعمل",
  pa_process_1: "التدقيق",
  pa_process_2: "الاستراتيجية",
  pa_process_3: "الإطلاق",
  pa_process_4: "التحسين",
  pa_process_5: "التوسيع",
  pa_benefits_title: "النتائج والمزايا",
  pa_benefits_1: "تكلفة نقرة أقل",
  pa_benefits_2: "معدلات تحويل أعلى",
  pa_benefits_3: "عائد أفضل على الإنفاق الإعلاني",
  pa_benefits_4: "توليد عملاء مؤهلين",
  pa_benefits_5: "حملات إعلانية قابلة للتوسيع",
  pa_benefits_6: "قرارات قائمة على البيانات",
  pa_faq_title: "الأسئلة الشائعة",
  pa_faq_1_q: "ما هي منصات الإعلانات التي تديرونها؟",
  pa_faq_1_a: "Meta (Facebook/Instagram) وGoogle Ads وTikTok Ads وLinkedIn Ads.",
  pa_faq_2_q: "ما هو الحد الأدنى لميزانية الإعلانات؟",
  pa_faq_2_a: "نوصي بحد أدنى 1,000$ شهريًا للحملات الفعالة.",
  pa_faq_3_q: "كيف تقيسون نجاح الحملة؟",
  pa_faq_3_a: "نتتبع ROAS وCPA وCTR والتحويلات ومؤشرات الأداء المخصصة.",
  pa_faq_4_q: "كم مرة سأتلقى التقارير؟",
  pa_faq_4_a: "تقارير أداء أسبوعية مع مراجعات شهرية شاملة.",
  pa_faq_5_q: "هل يمكنني إيقاف الحملات في أي وقت؟",
  pa_faq_5_a: "نعم، لديك السيطرة המלאة ويمكنك الإيقاف أو التعديل في أي وقت.",
  pa_faq_6_q: "هل تتعاملون مع إنتاج الإعلانات؟",
  pa_faq_6_a: "نعم، ننشئ جميع النصوص والمرئيات ومحتوى الفيديو داخليًا.",
  pa_cta_title: "جاهز للنمو؟",
  pa_cta_btn: "احجز مكالمة استراتيجية مجانية",
  pa_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== WEBSITE DESIGN (wd) ====================
  wd_hero_title: "تصميم المواقع",
  wd_hero_desc: "مواقع عالية التحويل وسريعة وجميلة مبنية لتحويل الزوار إلى عملاء.",
  wd_why_title: "لماذا تختارنا",
  wd_stat_1_num: "+450%",
  wd_stat_1_label: "زيادة التحويل",
  wd_stat_2_num: "99%",
  wd_stat_2_label: "ضمان وقت التشغيل",
  wd_stat_3_num: "14 يوم",
  wd_stat_3_label: "تسليم سريع",
  wd_deliver_title: "ما نقدمه",
  wd_deliver_1: "تصميم مخصص — تخطيطات فريدة مخصصة لعلامتك التجارية.",
  wd_deliver_2: "تطوير متجاوب — نهج يبدأ بالجوال.",
  wd_deliver_3: "تحسين SEO — تحسين تقني على الصفحة.",
  wd_deliver_4: "دمج CMS — إدارة محتوى سهلة.",
  wd_deliver_5: "إعداد المتجر الإلكتروني — تكوين متجر إلكتروني كامل.",
  wd_deliver_6: "تحسين السرعة — أداء تحميل سريع.",
  wd_process_title: "كيف نعمل",
  wd_process_1: "الاكتشاف",
  wd_process_2: "الإطار السلكي",
  wd_process_3: "التصميم",
  wd_process_4: "التطوير",
  wd_process_5: "الإطلاق",
  wd_benefits_title: "النتائج والمزايا",
  wd_benefits_1: "معدلات تحويل أعلى",
  wd_benefits_2: "تجربة مستخدم أفضل",
  wd_benefits_3: "تحسين ترتيب SEO",
  wd_benefits_4: "تصميم يبدأ بالجوال",
  wd_benefits_5: "سرعة تحميل سريعة",
  wd_benefits_6: "إدارة محتوى سهلة",
  wd_faq_title: "الأسئلة الشائعة",
  wd_faq_1_q: "ما هي منصات المواقع التي تبنون عليها؟",
  wd_faq_1_a: "WordPress وShopify وHTML/CSS/JS مخصص وحلول headless CMS.",
  wd_faq_2_q: "كم يستغرق بناء الموقع؟",
  wd_faq_2_a: "عادة 2-6 أسابيع حسب التعقيد والنطاق.",
  wd_faq_3_q: "هل تقدمون استضافة؟",
  wd_faq_3_a: "يمكننا إعداد وإدارة الاستضافة، أو العمل مع مزودك المفضل.",
  wd_faq_4_q: "هل سيكون متوافقًا مع الجوال؟",
  wd_faq_4_a: "بالطبع. جميع مواقعنا متجاوبة ومحسّنة للجوال.",
  wd_faq_5_q: "هل تقدمون صيانة للمواقع؟",
  wd_faq_5_a: "نعم، نقدم حزم صيانة ودعم مستمرة.",
  wd_faq_6_q: "هل يمكنني تحديث الموقع بنفسي؟",
  wd_faq_6_a: "نعم، نبني على منصات CMS سهلة الاستخدام ونقدم التدريب.",
  wd_cta_title: "جاهز للنمو؟",
  wd_cta_btn: "احجز مكالمة استراتيجية مجانية",
  wd_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== VIDEOGRAPHY (vg) ====================
  vg_hero_title: "التصوير المرئي السينمائي",
  vg_hero_desc: "إنتاج فيديو احترافي — تصوير مؤسسي وفعاليات ومقاطع منتجات.",
  vg_why_title: "لماذا تختارنا",
  vg_stat_1_num: "+600%",
  vg_stat_1_label: "زيادة التفاعل",
  vg_stat_2_num: "3.5x",
  vg_stat_2_label: "زيادة تذكر العلامة",
  vg_stat_3_num: "5 أيام",
  vg_stat_3_label: "سرعة في التسليم",
  vg_deliver_title: "ما نقدمه",
  vg_deliver_1: "فيديوهات مؤسسية — محتوى أعمال احترافي.",
  vg_deliver_2: "تغطية الفعاليات — توثيق كامل للفعاليات.",
  vg_deliver_3: "مقاطع منتجات — عرض منتجاتك أثناء العمل.",
  vg_deliver_4: "سرد العلامة التجارية — قصص سينمائية لعلامتك.",
  vg_deliver_5: "فيديوهات مقابلات — محتوى احترافي للتحدث.",
  vg_deliver_6: "لقطات درون — منظورات جوية.",
  vg_process_title: "كيف نعمل",
  vg_process_1: "التخطيط",
  vg_process_2: "الإنتاج",
  vg_process_3: "ما بعد الإنتاج",
  vg_process_4: "المراجعة",
  vg_process_5: "التسليم",
  vg_benefits_title: "النتائج والمزايا",
  vg_benefits_1: "جودة إنتاج احترافية",
  vg_benefits_2: "محتوى علامة تجارية لا يُنسى",
  vg_benefits_3: "مكتبة محتوى متعددة الاستخدامات",
  vg_benefits_4: "تفاعل جمهور أعلى",
  vg_benefits_5: "محتوى لعدة منصات",
  vg_benefits_6: "أصول بصرية طويلة الأمد",
  vg_faq_title: "الأسئلة الشائعة",
  vg_faq_1_q: "ما هي صيغ الفيديو التي تسلمونها؟",
  vg_faq_1_a: "4K و1080p وتنسيقات مخصصة بـ MP4 وMOV وProRes.",
  vg_faq_2_q: "هل تقدمون فريق الإنتاج؟",
  vg_faq_2_a: "نعم، نتعامل مع جميع احتياجات الإنتاج بما في ذلك الفريق والمعدات والlogistics.",
  vg_faq_3_q: "كم جولة مراجعة مضمنة؟",
  vg_faq_3_a: "نقدم حتى 3 جولات مراجعة في حزمنا المعيارية.",
  vg_faq_4_q: "هل يمكنكم التصوير في مكاني؟",
  vg_faq_4_a: "نعم، نصور في أي مكان أو في استوديونا الاحترافي.",
  vg_faq_5_q: "هل تقدمون اللقطات الخام؟",
  vg_faq_5_a: "تسليم اللقطات الخام متاح كخدمة إضافية.",
  vg_faq_6_q: "ما هي عملية الحجز؟",
  vg_faq_6_a: "تواصل معنا لمناقشة مشروعك وتلقي عرض سعر وحجز موعد التصوير.",
  vg_cta_title: "جاهز للنمو؟",
  vg_cta_btn: "احجز مكالمة استراتيجية مجانية",
  vg_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== PHOTOGRAPHY (ph) ====================
  ph_hero_title: "التصوير الفوتوغرافي التجاري",
  ph_hero_desc: "تصوير منتجات وبورتريه وتصوير تجاري عالي الجودة.",
  ph_why_title: "لماذا تختارنا",
  ph_stat_1_num: "+320%",
  ph_stat_1_label: "زيادة الجاذبية البصرية",
  ph_stat_2_num: "2.2x",
  ph_stat_2_label: "معدل النقر",
  ph_stat_3_num: "3 أيام",
  ph_stat_3_label: "تسليم سريع",
  ph_deliver_title: "ما نقدمه",
  ph_deliver_1: "تصوير منتجات — لقطات منتجات نظيفة واحترافية.",
  ph_deliver_2: "تصوير البورتريه — صور رسمية وصور فريق احترافية.",
  ph_deliver_3: "جولات تجارية — تصوير علامة تجارية وإعلاني.",
  ph_deliver_4: "تصوير نمط الحياة — لحظات علامة تجارية حقيقية.",
  ph_deliver_5: "تصوير المتاجر الإلكترونية — صور منتجات بخلفية بيضاء.",
  ph_deliver_6: "تحسين الصور — معالجة ما بعد احترافية.",
  ph_process_title: "كيف نعمل",
  ph_process_1: "المفهوم",
  ph_process_2: "التصوير",
  ph_process_3: "التعديل",
  ph_process_4: "المراجعة",
  ph_process_5: "التسليم",
  ph_benefits_title: "النتائج والمزايا",
  ph_benefits_1: "جودة صورة احترافية",
  ph_benefits_2: "مرئيات علامة تجارية متسقة",
  ph_benefits_3: "معدلات تحويل أعلى",
  ph_benefits_4: "مكتبة صور متعددة الاستخدامات",
  ph_benefits_5: "صور محسّنة لكل منصة",
  ph_benefits_6: "سرعة تسليم سريعة",
  ph_faq_title: "الأسئلة الشائعة",
  ph_faq_1_q: "كم عدد الصور المضمنة لكل جلسة تصوير؟",
  ph_faq_1_a: "حسب الحزمة، عادة 20-50+ صورة معدّلة لكل جلسة.",
  ph_faq_2_q: "هل تقدمون الإكسسوارات والتنسيق؟",
  ph_faq_2_a: "نعم، يمكننا ترتيب تنسيق المنتجات وتجهيز الإكسسوارات.",
  ph_faq_3_q: "ما هي صيغ الملفات التي تسلمونها؟",
  ph_faq_3_a: "JPG عالي الدقة وPNG وRAW حسب الطلب.",
  ph_faq_4_q: "هل تقدمون جولات تصوير في الموقع؟",
  ph_faq_4_a: "نعم، نصور في الموقع أو في استوديونا الاحترافي.",
  ph_faq_5_q: "كم يستغرق تحرير الصور؟",
  ph_faq_5_a: "التسليم العادي هو 3-5 أيام عمل بعد التصوير.",
  ph_faq_6_q: "هل يمكنكم مطابقة نمط تصوير محدد؟",
  ph_faq_6_a: "بالطبع. شارك رؤيتك وسنطابق النمط تمامًا.",
  ph_cta_title: "جاهز للنمو؟",
  ph_cta_btn: "احجز مكالمة استراتيجية مجانية",
  ph_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== MEDIA BUYING (mb) ====================
  mb_hero_title: "شراء الإعلانات الاستراتيجي",
  mb_hero_desc: "التخطيط والشراء الاستراتيجي للإعلانات عبر التلفزيون والرقمي.",
  mb_why_title: "لماذا تختارنا",
  mb_stat_1_num: "-35%",
  mb_stat_1_label: "تخفيض تكلفة الإعلانات",
  mb_stat_2_num: "5.2x",
  mb_stat_2_label: "عائد على الاستثمار",
  mb_stat_3_num: "+400%",
  mb_stat_3_label: "زيادة الوصول",
  mb_deliver_title: "ما نقدمه",
  mb_deliver_1: "التخطيط الإعلامي — اختيار استراتيجي للقنوات.",
  mb_deliver_2: "شراء التلفزيون — أماكن وطنية ومحلية.",
  mb_deliver_3: "شراء رقمي — أماكن programmatic ومباشرة.",
  mb_deliver_4: "حملات OOH — لوحات إعلانية وإعلانات النقل.",
  mb_deliver_5: "التفاوض — أفضل الأسعار والمواقع المميزة.",
  mb_deliver_6: "تتبع الأداء — تحليلات عبر القنوات.",
  mb_process_title: "كيف نعمل",
  mb_process_1: "البحث",
  mb_process_2: "التخطيط",
  mb_process_3: "الشراء",
  mb_process_4: "المراقبة",
  mb_process_5: "التحسين",
  mb_benefits_title: "النتائج والمزايا",
  mb_benefits_1: "تكاليف إعلانات أقل",
  mb_benefits_2: "وصول أوسع للجمهور",
  mb_benefits_3: "جودة مواقع أفضل",
  mb_benefits_4: "تناغم عبر القنوات",
  mb_benefits_5: "تخطيط قائم على البيانات",
  mb_benefits_6: "عائد على الاستثمار قابل للقياس",
  mb_faq_title: "الأسئلة الشائعة",
  mb_faq_1_q: "ما هي القنوات الإعلامية التي تغطونها؟",
  mb_faq_1_a: "التلفزيون والراديو والرقمي وتواصل الاجتماعي وOOH والمطبوعات والإعلانات programmatic.",
  mb_faq_2_q: "كيف تتفاوضون على أسعار الإعلام؟",
  mb_faq_2_a: "نستفيد من شبكتنا والحجم للحصول على أفضل الأسعار الممكنة.",
  mb_faq_3_q: "هل تتعاملون مع التخطيط والشراء معًا؟",
  mb_faq_3_a: "نعم، نقدم خدمات إعلامية شاملة من الاستراتيجية إلى التنفيذ.",
  mb_faq_4_q: "هل يمكنكم العمل بميزانية محددة؟",
  mb_faq_4_a: "بالطبع. نحسّن الخطط الإعلامية لتحقيق أقصى نتائج ضمن ميزانيتك.",
  mb_faq_5_q: "كيف تقيسون أداء الإعلام؟",
  mb_faq_5_a: "نتتبع الوصول والتردد وGRPs والتحويلات ومؤشرات الأداء المخصصة.",
  mb_faq_6_q: "هل تقدمون تقارير إعلامية؟",
  mb_faq_6_a: "نعم، نقدم تقارير حملات مفصلة مع أفكار عملية.",
  mb_cta_title: "جاهز للنمو؟",
  mb_cta_btn: "احجز مكالمة استراتيجية مجانية",
  mb_cta_whatsapp: "تواصل عبر واتساب",

  // ==================== BRIEF PAGE — COMMON ====================
  brief_progress: "التقدم",
  brief_continue: "التالي",
  brief_previous: "السابق",
  brief_review: "مراجعة وإرسال",
  brief_submit: "إرسال البريف",
  brief_save: "حفظ التقدم",
  brief_saved: "تم الحفظ",
  brief_success_title: "تم إرسال البريف!",
  brief_success_text: "شكرًا لك على إكمال البريف. سيراجع فريقنا طلبك ويرد عليك خلال 24 ساعة.",
  brief_back_home: "الرئيسية",
  brief_view_services: "شاهد الخدمات",
  brief_review_title: "مراجعة البريف",
  brief_step_review_your_brief: "مراجعة البريف",
  brief_desc_please_review_all_your_answers_before_submitting: "يرجى مراجعة جميع إجاباتك قبل الإرسال.",
  brief_desc_please_review_all_your_answers_before_submitting_you_can_go_back_to_make_changes: "يرجى مراجعة جميع إجاباتك قبل الإرسال. يمكنك العودة للتعديل.",

  // ==================== BRIEF — SHARED LABELS ====================
  brief_label_business_name: "اسم العمل",
  brief_ph_eg_vivedfx: "مثال: VIVEDFX",
  brief_label_industry: "القطاع",
  brief_label_target_audience: "الجمهور المستهدف",
  brief_label_competitors: "المنافسون",
  brief_label_additional_notes: "ملاحظات إضافية",
  brief_label_budget_range: "نطاق الميزانية",
  brief_label_deadline: "الموعد النهائي",

  // ==================== BRIEF — INDUSTRY OPTIONS ====================
  brief_select_select_your_industry: "اختر قطاعك",
  brief_option_healthcare_medical: "الرعاية الصحية والطب",
  brief_option_fitness_wellness: "اللياقة والصحة",
  brief_option_corporate_b2b: "المؤسسات والشركات",
  brief_option_ecommerce_retail: "التجارة الإلكترونية والتجزئة",
  brief_option_real_estate: "العقارات",
  brief_option_food_beverage: "الأغذية والمشروبات",
  brief_option_education: "التعليم",
  brief_option_technology_saas: "التكنولوجيا والبرمجيات",
  brief_option_automotive: "السيارات",
  brief_option_fashion_beauty: "الأزياء والجمال",
  brief_option_hospitality_travel: "الضيافة والسفر",
  brief_option_other: "أخرى",
  brief_option_legal_financial: "القانونية والمالية",

  // ==================== BRIEF — BUDGET OPTIONS ====================
  brief_select_select_your_budget_range: "اختر نطاق ميزانيتك",
  brief_option_under_500: "أقل من $500",
  brief_option_500_1000: "$500 - $1,000",
  brief_option_under_1000: "أقل من $1,000",
  brief_option_1000_3000: "$1,000 - $3,000",
  brief_option_3000_5000: "$3,000 - $5,000",
  brief_option_5000_10000: "$5,000 - $10,000",
  brief_option_10000: "$10,000+",
  brief_option_10000_20000: "$10,000 - $20,000",
  brief_option_20000: "$20,000+",
  brief_option_not_sure_yet: "لم أقرر بعد",

  // ==================== BRIEF — MONTHLY BUDGET OPTIONS ====================
  brief_option_under_500month: "أقل من $500/شهريًا",
  brief_option_500_1000month: "$500 - $1,000/شهريًا",
  brief_option_1000_3000month: "$1,000 - $3,000/شهريًا",
  brief_option_3000_5000month: "$3,000 - $5,000/شهريًا",
  brief_option_5000_10000month: "$5,000 - $10,000/شهريًا",
  brief_option_5000month: "$5,000+/شهريًا",
  brief_option_10000month: "$10,000+/شهريًا",
  brief_option_under_1000month: "أقل من $1,000/شهريًا",

  // ==================== BRIEF — PLATFORM OPTIONS ====================
  brief_option_instagram: "Instagram",
  brief_option_facebook: "Facebook",
  brief_option_tiktok: "TikTok",
  brief_option_linkedin: "LinkedIn",
  brief_option_twitter_x: "Twitter / X",
  brief_option_youtube: "YouTube",
  brief_option_pinterest: "Pinterest",
  brief_option_snapchat: "Snapchat",
  brief_option_website: "الموقع الإلكتروني",
  brief_option_email: "البريد الإلكتروني",

  // ==================== BRIEF — GOAL OPTIONS ====================
  brief_option_brand_awareness: "التوعية بالعلامة التجارية",
  brief_option_lead_generation: "توليد العملاء المحتملين",
  brief_option_sales_conversions: "المبيعات والتحويلات",
  brief_option_community_engagement: "تفاعل المجتمع",
  brief_option_website_traffic: "زيارات الموقع",
  brief_option_all_of_the_above: "جميع ما سبق",
  brief_option_engagement: "التفاعل",
  brief_option_app_installs: "تحميل التطبيقات",
  brief_option_conversions_sales: "التحويلات / المبيعات",

  // ==================== BRIEF — CONTENT STYLE OPTIONS ====================
  brief_option_professional_polished: "مهني وأنيق",
  brief_option_casual_friendly: "ودي ومرح",
  brief_option_bold_edgy: "جريء وحاد",
  brief_option_minimal_clean: "بسيط ونظيف",
  brief_option_luxury_premium: "فاخر ومتميز",

  // ==================== BRIEF — BRAND VOICE OPTIONS ====================
  brief_option_professional: "مهني",
  brief_option_friendly_casual: "ودي ومرح",
  brief_option_authoritative: "سلطة",
  brief_option_playful_fun: "مرح وممتع",

  // ==================== BRIEF — VISUAL STYLE OPTIONS ====================
  brief_option_modern_minimal: "عصري وبسيط",
  brief_option_classic_timeless: "كلاسيكي وخالد",
  brief_option_bold_expressive: "جريء وتعبير",
  brief_option_tech_futuristic: "تقني ومستقبلي",
  brief_option_bold_dynamic: "جريء وديناميكي",
  brief_option_corporate_professional: "مؤسسي ومهني",
  brief_option_creative_artistic: "إبداعي وفني",
  brief_option_tech_modern: "تقني وعصري",

  // ==================== BRIEF — EDITING STYLE OPTIONS ====================
  brief_option_cinematic_dramatic: "سينمائي ودرامي",
  brief_option_clean_modern: "نظيف وعصري",
  brief_option_fastpaced_energetic: "سريع وحيوي",
  brief_option_minimal_elegant: "بسيط وأنيق",
  brief_option_documentary_style: "توثيقي",

  // ==================== BRIEF — VOLUME / QUANTITY OPTIONS ====================
  brief_select_select_volume: "اختر الكمية",
  brief_option_12_posts_per_week: "1-2 منشورات أسبوعيًا",
  brief_option_34_posts_per_week: "3-4 منشورات أسبوعيًا",
  brief_option_daily_posts: "منشورات يومية",
  brief_option_multiple_posts_per_day: "عدة منشورات يوميًا",
  brief_option_not_sure_need_recommendation: "لم أقرر — أحتاج توصية",
  brief_select_select_quantity: "اختر الكمية",
  brief_option_14_pieces_per_month: "1-4 قطع شهريًا",
  brief_option_510_pieces_per_month: "5-10 قطع شهريًا",
  brief_option_1020_pieces_per_month: "10-20 قطعة شهريًا",
  brief_option_20_pieces_per_month: "20+ قطعة شهريًا",
  brief_option_need_recommendation: "أحتاج توصية",

  // ==================== BRIEF — CONTENT TYPE OPTIONS ====================
  brief_option_social_media_posts: "منشورات التواصل الاجتماعي",
  brief_option_blog_articles: "مقالات المدونة",
  brief_option_email_marketing: "التسويق عبر البريد الإلكتروني",
  brief_option_ad_copy: "نصوص الإعلانات",
  brief_option_website_copy: "نصوص الموقع الإلكتروني",
  brief_option_video_scripts: "نصوص الفيديو",
  brief_option_presentations: "العروض التقديمية",
  brief_option_infographics: "الرسوم البيانية",

  // ==================== BRIEF — VIDEO TYPE OPTIONS ====================
  brief_option_brand_company_profile: "ملف العلامة / الشركة",
  brief_option_product_demo: "عرض المنتج",
  brief_option_social_media_video: "فيديو التواصل الاجتماعي",
  brief_option_commercial_ad: "إعلان تجاري",
  brief_option_tutorial_howto: "شرح / كيف",
  brief_option_event_coverage: "تغطية فعالية",
  brief_option_testimonial_interview: "شهادة / مقابلة",
  brief_option_motion_graphics_animation: "رسوم متحركة / أنيميشن",

  // ==================== BRIEF — DURATION OPTIONS ====================
  brief_select_select_target_duration: "اختر المدة المستهدفة",
  brief_option_under_15_seconds_reeltiktok: "أقل من 15 ثانية (ريل/تيك توك)",
  brief_option_1530_seconds_adsocial: "15-30 ثانية (إعلان/اجتماعي)",
  brief_option_3060_seconds_promo: "30-60 ثانية (ترويجي)",
  brief_option_12_minutes_profiledemo: "1-2 دقيقة (ملف/عرض)",
  brief_option_25_minutes_documentary_style: "2-5 دقائق (أسلوب وثائقي)",
  brief_option_5_minutes_long_form: "5+ دقائق (طويل)",

  // ==================== BRIEF — SHOOT TYPE OPTIONS ====================
  brief_option_product_photography: "تصوير منتجات",
  brief_option_corporate_headshots: "صور مؤسسية / شخصية",
  brief_option_lifestyle_brand: "أسلوب حياة / علامة تجارية",
  brief_option_real_estate_interior: "عقارات / ديكور داخلي",
  brief_option_fashion_apparel: "أزياء وملابس",

  // ==================== BRIEF — INDOOR/OUTDOOR OPTIONS ====================
  brief_option_indoor: "داخلي",
  brief_option_outdoor: "خارجي",
  brief_option_both: "كلاهما",

  // ==================== BRIEF — WEBSITE PURPOSE OPTIONS ====================
  brief_option_brochure_info_site: "كتيب / موقع معلوماتي",
  brief_option_ecommerce_online_store: "تجارة إلكترونية / متجر",
  brief_option_booking_appointment: "حجز / مواعيد",
  brief_option_portfolio_showcase: "معرض أعمال",
  brief_option_saas_app_landing: "SaaS / صفحة تطبيق",

  // ==================== BRIEF — PAGE OPTIONS ====================
  brief_option_home: "الرئيسية",
  brief_option_about_us: "من نحن",
  brief_option_services: "الخدمات",
  brief_option_portfolio_work: "أعمالنا",
  brief_option_blog: "المدونة",
  brief_option_contact: "اتصل بنا",
  brief_option_pricing: "الأسعار",
  brief_option_faq: "الأسئلة الشائعة",
  brief_option_team: "الفريق",
  brief_option_testimonials: "شهادات العملاء",
  brief_option_careers: "الوظائف",
  brief_option_custom_page: "صفحة مخصصة",

  // ==================== BRIEF — FEATURE OPTIONS ====================
  brief_option_contact_form: "نموذج اتصال",
  brief_option_newsletter_signup: "اشتراك النشرة الإخبارية",
  brief_option_live_chat: "محادثة مباشرة",
  brief_option_social_media_feed: "خلاصة وسائل التواصل",
  brief_option_analytics_dashboard: "لوحة تحليلات",
  brief_option_multilanguage: "متعدد اللغات",
  brief_option_custom_animations: "أنيميشن مخصص",
  brief_option_cms_content_management: "إدارة المحتوى (CMS)",

  // ==================== BRIEF — BOOKING / PAYMENT OPTIONS ====================
  brief_option_yes_i_need_a_booking_system: "نعم، أحتاج نظام حجز",
  brief_option_maybe_in_the_future: "ربما في المستقبل",
  brief_option_no: "لا",
  brief_option_stripe: "Stripe",
  brief_option_paypal: "PayPal",
  brief_option_local_payment_gateway: "بوابة دفع محلية",
  brief_option_not_needed: "غير مطلوب",

  // ==================== BRIEF — LANGUAGE OPTIONS ====================
  brief_option_english_only: "الإنجليزية فقط",
  brief_option_arabic_english: "العربية + الإنجليزية",

  // ==================== BRIEF — SEO OPTIONS ====================
  brief_option_onpage_seo: "SEO على الصفحة",
  brief_option_technical_seo: "SEO تقني",
  brief_option_local_seo: "SEO محلي",
  brief_option_schema_markup: "Schema Markup",
  brief_option_speed_optimization: "تحسين السرعة",

  // ==================== BRIEF — HOSTING OPTIONS ====================
  brief_option_i_have_hosting: "لدي استضافة",
  brief_option_need_hosting_setup: "أحتاج إعداد استضافة",
  brief_option_not_sure: "لست متأكدًا",

  // ==================== BRIEF — PIXEL / TRACKING OPTIONS ====================
  brief_option_yes_installed: "نعم، مثبت",
  brief_option_yes_fully_set_up: "نعم، مُعد بالكامل",
  brief_option_partial_setup: "إعداد جزئي",
  brief_option_no_tracking_in_place: "لا يوجد تتبع",
  brief_option_yes_connected: "نعم، متصل",

  // ==================== BRIEF — ANALYTICS OPTIONS ====================
  brief_option_ga4_installed: "GA4 مثبت",
  brief_option_old_analytics_ua: "التحليلات القديمة (UA)",
  brief_option_no_analytics: "لا توجد تحليلات",

  // ==================== BRIEF — SCRIPT / ACTOR / DRONE / VO OPTIONS ====================
  brief_option_yes_i_have_a_script: "نعم، لدي نص",
  brief_option_i_have_a_rough_idea: "لدي فكرة عامة",
  brief_option_no_need_script_writing: "لا، أحتاج كتابة نص",
  brief_option_yes_provide_actors: "نعم، وفر ممثلين",
  brief_option_well_use_our_own_team: "سنستخدم فريقنا",
  brief_option_no_actors_needed: "لا أحتاج ممثلين",
  brief_option_yes_aerial_footage_needed: "نعم، أحتاج لقطات جوية",
  brief_option_no_drone_needed: "لا أحتاج درون",
  brief_option_yes_male_vo: "نعم، تعليق صوتي ذكر",
  brief_option_yes_female_vo: "نعم، تعليق صوتي أنثى",
  brief_option_no_voice_over: "بدون تعليق صوتي",

  // ==================== BRIEF — AD PLATFORM OPTIONS ====================
  brief_option_google_ads: "إعلانات Google",
  brief_option_facebook_ads: "إعلانات Facebook",
  brief_option_instagram_ads: "إعلانات Instagram",
  brief_option_tiktok_ads: "إعلانات TikTok",
  brief_option_linkedin_ads: "إعلانات LinkedIn",
  brief_option_snapchat_ads: "إعلانات Snapchat",
  brief_option_none_starting_fresh: "لا شيء (بدء من الصفر)",

  // ==================== BRIEF — UPLOAD / HINT ====================
  brief_label_upload_reference_files: "رفع ملفات مرجعية",
  brief_upload_drop_files_here_or_click_to_upload: "أسقط الملفات هنا أو انقر للرفع",
  brief_hint_pdf_docx_jpg_png_ai_psd_zip_max_10_files: "PDF وDOCX وJPG وPNG وAI وPSD وZIP — الحد الأقصى 10 ملفات",
  brief_label_upload_existing_logo: "رفع الشعار الحالي",
  brief_upload_drop_your_existing_logo_here: "أسقط شعارك الحالي هنا",
  brief_hint_pdf_ai_psd_png_jpg_max_10_files: "PDF وAI وPSD وPNG وJPG — الحد الأقصى 10 ملفات",
  brief_label_upload_brand_assets: "رفع أصول العلامة التجارية",
  brief_upload_drop_brand_assets_here: "أسقط أصول العلامة التجارية هنا",
  brief_hint_guidelines_color_palettes_typography_patterns_max_10_files: "الأدلة والألوان والخطوط والأنماط — الحد الأقصى 10 ملفات",
  brief_label_upload_files: "رفع الملفات",

  // ==================== BRIEF — SOCIAL MEDIA PAGE ====================
  brief_social_media_step_about_your_business: "عن عملك",
  brief_desc_lets_start_with_the_basics_so_we_understand_who_you_are: "لنبدأ بالأساسيات لفهم من أنت.",
  brief_ph_describe_your_ideal_customer_age_gender_interests_pain_points: "صف العميل المثالي — العمر والجنس والاهتمامات ونقاط الألم...",
  brief_step_current_social_presence: "الحضور الحالي على التواصل الاجتماعي",
  brief_desc_help_us_understand_where_you_currently_stand_on_social_media: "ساعدنا في فهم وضعك الحالي على وسائل التواصل الاجتماعي.",
  brief_label_current_social_media_accounts: "حسابات التواصل الاجتماعي الحالية",
  brief_ph_list_your_social_media_profiles_and_follower_counts_eg_instagram_vivedfx_5k_followers: "اذكر حسابات التواصل الاجتماعي وعدد المتابعين (مثال: Instagram: @vivedfx — 5 آلاف متابع)",
  brief_label_biggest_challenges: "أكبر التحديات",
  brief_ph_what_are_you_struggling_with_most_on_social_media_eg_low_engagement_inconsistent_posting_no_strategy: "ما هي أصعب ما تواجهه على التواصل الاجتماعي؟ (مثل: تفاعل منخفض، نشر غير منتظم، لا استراتيجية)",
  brief_ph_list_35_competitors_or_brands_you_admire_on_social_media: "اذكر 3-5 منافسين أو علامات تجارية تفضلها على التواصل الاجتماعي",
  brief_step_goals_strategy: "الأهداف والاستراتيجية",
  brief_desc_what_do_you_want_to_achieve_with_social_media_marketing: "ماذا تريد تحقيقه من التسويق عبر التواصل الاجتماعي؟",
  brief_label_primary_goals: "الأهداف الرئيسية",
  brief_label_platforms_required: "المنصات المطلوبة",
  brief_step_content_brand: "المحتوى والعلامة التجارية",
  brief_desc_how_should_your_brand_look_and_feel_on_social_media: "كيف يجب أن تبدو علامتك التجارية على التواصل الاجتماعي؟",
  brief_label_preferred_content_style: "نمط المحتوى المفضل",
  brief_label_brand_personality: "شخصية العلامة التجارية",
  brief_ph_describe_your_brand_in_35_adjectives_eg_modern_bold_trustworthy_playful: "صف علامتك التجارية بـ 3-5 صفات (مثل: عصري، جريء، موثوق، مرعب)",
  brief_label_monthly_content_needed: "المحتوى الشهري المطلوب",
  brief_step_budget_extras: "الميزانية والمميزات الإضافية",
  brief_desc_help_us_tailor_a_package_that_fits_your_needs_and_budget: "ساعدنا في تخصيص حزمة تناسب احتياجاتك وميزانيتك.",
  brief_label_monthly_marketing_budget: "ميزانية التسويق الشهرية",
  brief_ph_anything_else_youd_like_us_to_know_special_requirements_deadlines_references: "أي شيء آخر تريد إخبارنا به؟ متطلبات خاصة، مواعيد نهائية، مراجع...",

  // ==================== BRIEF — BRANDING PAGE ====================
  brief_step_brand_foundation: "أساسيات العلامة التجارية",
  brief_desc_tell_us_the_story_behind_your_brand_what_drives_you_and_where_youre_headed: "أخبرنا بالقصة وراء علامتك التجارية — ما الذي يحركك وإلى أين أنت ذاهب.",
  brief_label_brand_story: "قصة العلامة التجارية",
  brief_ph_how_did_your_brand_start_whats_the_journey_behind_it: "كيف بدأت علامتك التجارية؟ ما هي الرحلة وراءها؟",
  brief_label_mission: "المهمة",
  brief_ph_what_is_your_companys_mission_why_do_you_exist: "ما هي مهمة شركتك؟ لماذا توجد؟",
  brief_label_vision: "الرؤية",
  brief_ph_where_do_you_see_your_brand_in_510_years: "أين ترى علامتك التجارية خلال 5-10 سنوات؟",
  brief_label_core_values: "القيم الأساسية",
  brief_ph_list_35_core_values_that_define_your_brand_eg_innovation_integrity_excellence: "اذكر 3-5 قيم أساسية تحدد علامتك التجارية (مثل: الابتكار، النزاهة، التميز)",
  brief_step_target_audience: "الجمهور المستهدف",
  brief_desc_who_are_you_trying_to_reach_the_more_specific_the_better: "من تريد الوصول إليه؟ كلما كان التحديد أكثر دقة كان أفضل.",
  brief_ph_describe_your_ideal_customer_demographics_psychographics_behaviors_pain_points: "صف العميل المثالي — الديموغرافيا والسيكوجرافيا والسلوكيات ونقاط الألم",
  brief_step_visual_direction: "الاتجاه البصري",
  brief_desc_what_should_your_brand_look_and_feel_like: "كيف يجب أن تبدو وتشعر علامتك التجارية؟",
  brief_label_preferred_style: "النمط المفضل",
  brief_label_preferred_colors: "الألوان المفضلة",
  brief_ph_eg_dark_blue_gold_accents_or_describe_the_mood: "مثال: أزرق داكن، لمسات ذهبية — أوصف المزاج",
  brief_label_colors_to_avoid: "الألوان المطلوب تجنبها",
  brief_ph_eg_no_bright_pink_no_neon_green: "مثال: بدون وردي فاقح، بدون أخضر نيون",
  brief_step_logo_and_inspiration: "الشعار والإلهام",
  brief_desc_share_any_logo_ideas_or_brand_references_that_inspire_you: "شارك أي أفكار شعار أو مراجع تجارية تلهمك.",
  brief_label_logo_inspiration: "إلهام الشعار",
  brief_ph_describe_any_logo_ideas_you_have_style_symbols_layouts_or_share_links_to_references: "صف أي أفكار شعار لديك — النمط، الرموز، التخطيطات، أو شارك روابط مراجع",
  brief_label_brand_references: "المراجع التجارية",
  brief_ph_list_brands_whose_identity_you_admire_eg_apple_nike_aesop: "اذكر علامات تجارية تفضل هويتها (مثل: Apple، Nike، Aesop)",
  brief_step_additional_details: "تفاصيل إضافية",
  brief_desc_anything_else_that_will_help_us_create_the_perfect_brand_identity: "أي شيء آخر سيساعدنا في إنشاء هوية العلامة التجارية المثالية.",
  brief_ph_eg_within_4_weeks_no_rush: "مثال: خلال 4 أسابيع، بدون استعجال",
  brief_ph_anything_else_youd_like_us_to_know: "أي شيء آخر تريد إخبارنا به؟",

  // ==================== BRIEF — CONTENT CREATION PAGE ====================
  brief_step_content_type_and_audience: "نوع المحتوى والجمهور",
  brief_desc_what_kind_of_content_do_you_need_and_who_is_it_for: "ما نوع المحتوى الذي تحتاجه ومن الجمهور المستهدف؟",
  brief_label_content_type: "نوع المحتوى",
  brief_label_platforms: "المنصات",
  brief_ph_who_are_you_creating_this_content_for: "لمن تنشئ هذا المحتوى؟",
  brief_step_brand_and_style: "العلامة التجارية والنمط",
  brief_desc_how_should_your_content_look_and_feel: "كيف يجب أن يبدو ويشعر محتواك؟",
  brief_label_brand_voice: "صوت العلامة التجارية",
  brief_label_preferred_style: "النمط المفضل",
  brief_ph_describe_the_visual_or_writing_style_you_prefer_eg_clean_with_bold_headlines_minimal_with_lots_of_white_space: "صف النمط البصري أو الكتابي المفضل (مثل: نظيف مع عناوين جريئة، بسيط مع مساحة بيضاء كثيرة)",
  brief_label_cta_style: "نمط الدعوة للعمل",
  brief_ph_how_do_you_want_to_prompt_action_eg_soft_and_informative_direct_and_urgent_playful: "كيف تريد تحفيز الإجراء؟ (مثل: هادئ ومعلوماتي، مباشر وعاجل، مرح)",
  brief_step_topics_and_deliverables: "المواضيع والمخرجات",
  brief_desc_what_should_we_create_and_how_much: "ماذا يجب أن ننشئ وكم الكمية؟",
  brief_label_monthly_deliverables: "المخرجات الشهرية",
  brief_label_topics_themes: "المواضيع والسمات",
  brief_ph_what_topics_should_we_cover_list_themes_product_highlights_seasonal_content_ideas: "ما المواضيع التي يجب أن نغطيها؟ اذكر السمات وتسليط الضوء على المنتجات وأفكار المحتوى الموسمية...",
  brief_ph_list_competitors_whose_content_you_admire_what_do_you_like_about_their_content: "اذكر منافسين تفضل محتواه. ما الذي يعجبك في محتواهم؟",
  brief_label_references: "المراجع",
  brief_ph_share_any_examples_of_content_you_love_links_screenshots_or_descriptions: "شارك أي أمثلة على محتوى تحبه — روابط أو لقطات شاشة أو أوصاف",
  brief_step_budget_and_extras: "الميزانية والمميزات الإضافية",
  brief_desc_final_details_to_get_started: "التفاصيل النهائية للبدء.",
  brief_ph_anything_else_special_requirements_brand_guidelines_content_calendar: "أي شيء آخر؟ متطلبات خاصة، أدلة العلامة التجارية، تقويم المحتوى...",

  // ==================== BRIEF — VIDEOGRAPHY PAGE ====================
  brief_step_video_details: "تفاصيل الفيديو",
  brief_desc_tell_us_about_the_video_you_need: "أخبرنا عن الفيديو الذي تحتاجه.",
  brief_label_video_type: "نوع الفيديو",
  brief_label_objective: "الهدف",
  brief_ph_what_should_this_video_achieve_eg_increase_brand_awareness_explain_our_service_drive_sales: "ماذا يجب أن يحقق هذا الفيديو؟ (مثل: زيادة التوعية بالعلامة، شرح خدمتنا، زيادة المبيعات)",
  brief_label_duration: "المدة",
  brief_step_production_requirements: "متطلبات الإنتاج",
  brief_desc_what_do_we_need_to_bring_to_the_shoot: "ماذا نحتاج إحضاره للتصوير؟",
  brief_label_shooting_location: "موقع التصوير",
  brief_ph_eg_our_office_outdoor_location_studio_multiple_locations: "مثال: مكتبنا، موقع خارجي، استوديو، مواقع متعددة",
  brief_label_script_available: "هل يوجد نص؟",
  brief_label_actors_needed: "هل تحتاج ممثلين؟",
  brief_label_drone_needed: "هل تحتاج درون؟",
  brief_label_voice_over_needed: "هل تحتاج تعليق صوتي؟",
  brief_step_editing_and_references: "التحرير والمراجع",
  brief_desc_how_should_the_final_video_look: "كيف يجب أن يبدو الفيديو النهائي؟",
  brief_label_editing_style: "نمط التحرير",
  brief_ph_paste_urls_of_videos_you_like_or_describe_the_look_and_feel_you_want: "الصق روابط فيديوهات تعجبك أوصف المظهر والشعور الذي تريده",
  brief_ph_eg_need_final_video_by_march_20: "مثال: أحتاج الفيديو النهائي بحلول 20 مارس",
  brief_desc_final_details_to_wrap_up_your_brief: "التفاصيل النهائية لإتمام البريف.",

  // ==================== BRIEF — PHOTOGRAPHY PAGE ====================
  brief_step_shoot_details: "تفاصيل التصوير",
  brief_desc_tell_us_about_the_photoshoot_you_need: "أخبرنا عن جلسة التصوير التي تحتاجها.",
  brief_label_business_type: "نوع العمل",
  brief_ph_eg_restaurant_gym_fashion_brand_corporate_office: "مثال: مطعم، صالة رياضية، علامة أزياء، مكتب مؤسسي",
  brief_label_shoot_type: "نوع التصوير",
  brief_label_products_or_services: "المنتجات أو الخدمات",
  brief_ph_what_exactly_do_you_need_photographed_describe_the_products_services_or_scenes: "ما الذي تحتاج تحديده بالتصوير؟ صف المنتجات أو الخدمات أو المشاهد.",
  brief_step_location_and_setup: "الموقع والإعداد",
  brief_desc_where_and_how_will_the_shoot_take_place: "أين وكيف ستتم جلسة التصوير؟",
  brief_ph_eg_our_studio_clients_office_outdoor_park_restaurant: "مثال: استوديونا، مكتب العميل، حديقة خارجية، مطعم",
  brief_label_indoor_or_outdoor: "داخلي أم خارجي؟",
  brief_label_number_of_products: "عدد المنتجات",
  brief_ph_eg_15_products_3_categories: "مثال: 15 منتج، 3 فئات",
  brief_label_number_of_team_members: "عدد أعضاء الفريق",
  brief_ph_eg_5_people_for_headshots: "مثال: 5 أشخاص للصور الشخصية",
  brief_step_style_and_delivery: "النمط والتسليم",
  brief_desc_what_look_are_you_going_for: "أي مظهر تبحث عنه؟",
  brief_label_style_references: "مراجع النمط",
  brief_ph_describe_the_photography_style_you_want_or_paste_links_to_examples_you_love: "صف نمط التصوير الذي تريده، أو الصق روابط لأمثلة تعجبك",
  brief_label_delivery_date: "تاريخ التسليم",
  brief_ph_eg_within_2_weeks_need_by_march_15: "مثال: خلال أسبوعين، أحتاج بحلول 15 مارس",
  brief_ph_anything_else_mood_color_grading_retouching_level_number_of_final_images: "أي شيء آخر؟ المزاج، تصحيح الألوان، مستوى المعالجة، عدد الصور النهائية...",

  // ==================== BRIEF — WEBSITE PAGE ====================
  brief_step_business_and_purpose: "العمل والغرض",
  brief_desc_tell_us_about_your_business_and_what_you_need_the_website_to_achieve: "أخبرنا عن عملك وما تحتاج الموقع لتحقيقه.",
  brief_label_business_information: "معلومات العمل",
  brief_ph_business_name_what_you_do_location_years_in_business: "اسم العمل، ماذا تفعل، الموقع، سنوات العمل...",
  brief_label_website_purpose: "غرض الموقع",
  brief_ph_who_is_this_website_for_describe_your_ideal_visitor: "لمن هذا الموقع؟ صف الزائر المثالي.",
  brief_step_pages_and_features: "الصفحات والمميزات",
  brief_desc_what_pages_and_features_do_you_need: "ما الصفحات والمميزات التي تحتاجها؟",
  brief_label_required_pages: "الصفحات المطلوبة",
  brief_label_required_features: "المميزات المطلوبة",
  brief_step_ecommerce_and_integrations: "التجارة الإلكترونية والتكاملات",
  brief_desc_do_you_need_online_selling_or_booking_capabilities: "هل تحتاج إمكانيات البيع أو الحجز عبر الإنترنت؟",
  brief_label_booking_system: "نظام الحجز؟",
  brief_label_payment_gateway: "بوابة الدفع؟",
  brief_label_languages: "اللغات",
  brief_step_design_and_references: "التصميم والمراجع",
  brief_desc_show_us_what_you_like_so_we_can_match_your_vision: "أرنا ما يعجبك لنتمكن من تحقيق رؤيتك.",
  brief_label_style_preference: "تفضيل النمط",
  brief_label_reference_websites: "مواقع مرجعية",
  brief_ph_paste_urls_of_websites_you_like_and_tell_us_what_you_like_about_them: "الصق روابط مواقع تعجبك وأخبرنا ما الذي يعجبك فيها",
  brief_step_technical_and_seo: "التقنية وSEO",
  brief_desc_tell_us_about_your_technical_requirements_and_seo_goals: "أخبرنا عن متطلباتك التقنية وأهداف SEO.",
  brief_label_seo_requirements: "متطلبات SEO",
  brief_label_domain: "النطاق",
  brief_ph_eg_yourbusinesscom_or_need_help_choosing: "مثال: yourbusiness.com — أو 'أحتاج مساعدة في الاختيار'",
  brief_label_hosting: "الاستضافة",
  brief_step_budget_and_timeline: "الميزانية والجدول الزمني",
  brief_desc_when_do_you_need_this_and_whats_your_budget: "متى تحتاج هذا وما هي ميزانيتك؟",
  brief_ph_eg_launch_by_march_1st_asap_no_rush: "مثال: إطلاق بحلول 1 مارس، ASAP، بدون استعجال",
  brief_ph_anything_else_special_features_integrations_existing_content: "أي شيء آخر؟ مميزات خاصة، تكاملات، محتوى موجود...",

  // ==================== BRIEF — CONSULTATION PAGE ====================
  brief_step_about_your_business: "عن عملك",
  brief_desc_give_us_a_snapshot_of_your_business_and_where_it_stands_today: "أعطنا نظرة عامة على عملك ووضعه الحالي.",
  brief_label_current_situation: "الوضع الحالي",
  brief_ph_describe_where_your_business_is_right_now_revenue_team_size_market_position_growth_stage: "صف وضع عملك الحالي — الإيرادات، حجم الفريق، التموضع في السوق، مرحلة النمو...",
  brief_label_main_challenges: "التحديات الرئيسية",
  brief_ph_what_are_the_biggest_challenges_youre_facing_right_now: "ما هي أكبر التحديات التي تواجهها حاليًا؟",
  brief_step_goals_and_vision: "الأهداف والرؤية",
  brief_desc_where_do_you_want_to_take_your_business: "إلى أين تريد قيادة عملك؟",
  brief_label_goals: "الأهداف",
  brief_ph_what_do_you_want_to_achieve_shortterm_and_longterm_goals: "ماذا تريد تحقيقه؟ أهداف قصيرة وطويلة المدى.",
  brief_label_budget: "الميزانية",
  brief_label_timeline: "الجدول الزمني",
  brief_ph_eg_need_to_see_results_in_3_months_longterm_partnership: "مثال: أحتاج رؤية نتائج خلال 3 أشهر، شراكة طويلة المدى",
  brief_ph_anything_else_youd_like_us_to_know_before_the_consultation: "أي شيء آخر تريد إخبارنا به قبل الاستشارة؟",

  // ==================== BRIEF — PERFORMANCE MARKETING PAGE ====================
  brief_step_business_overview: "نظرة عامة على العمل",
  brief_desc_tell_us_about_your_business_and_current_advertising_setup: "أخبرنا عن عملك وإعدادات الإعلانات الحالية.",
  brief_ph_what_are_you_selling_describe_your_main_products_or_services: "ماذا تبيع؟ صف منتجاتك أو خدماتك الرئيسية.",
  brief_label_current_advertising_platforms: "منصات الإعلانات الحالية",
  brief_step_budget_and_campaigns: "الميزانية والحملات",
  brief_desc_help_us_understand_your_budget_and_past_campaign_performance: "ساعدنا في فهم ميزانيتك وأداء الحملات السابقة.",
  brief_label_monthly_ad_budget: "ميزانية الإعلانات الشهرية",
  brief_label_previous_campaigns: "الحملات السابقة",
  brief_ph_have_you_run_ads_before_what_were_the_results_any_data_or_screenshots_you_can_share: "هل أجريت إعلانات من قبل؟ ما هي النتائج؟ أي بيانات أو لقطات شاشة يمكنك مشاركتها؟",
  brief_label_landing_pages: "صفحات الهبوط",
  brief_ph_do_you_have_existing_landing_pages_paste_urls_or_describe_them: "هل لديك صفحات هبوط موجودة؟ الصق الروابط أو صفها.",
  brief_step_targeting: "الاستهداف",
  brief_desc_who_are_you_trying_to_reach_with_your_ads: "من تريد الوصول إليه بإعلاناتك؟",
  brief_label_target_locations: "المواقع المستهدفة",
  brief_ph_eg_usa_nationwide_nyc_metro_area_worldwide: "مثال: الولايات المتحدة بأكملها، منطقة نيويورك، عالميًا",
  brief_ph_list_competitors_who_are_also_running_ads_any_insights_on_their_approach: "اذكر منافسين أيضًا يجرون إعلانات. أي ملاحظات على نهجهم؟",
  brief_step_tracking_and_technical: "التتبع والتقنية",
  brief_desc_tell_us_about_your_current_tracking_setup: "أخبرنا عن إعداد التتبع الحالي.",
  brief_label_existing_pixel: "بكسل موجود؟",
  brief_label_existing_conversion_tracking: "تتبع تحويلات موجود؟",
  brief_label_main_objective: "الهدف الرئيسي",
  brief_step_kpis_and_extras: "مؤشرات الأداء والمميزات الإضافية",
  brief_desc_what_metrics_matter_most_to_you: "ما هي المقاييس التي تهمك أكثر؟",
  brief_label_key_performance_indicators_kpis: "مؤشرات الأداء الرئيسية (KPIs)",
  brief_ph_what_metrics_do_you_want_us_to_optimize_for_eg_cost_per_lead_roas_ctr_cpa: "ما هي المقاييس التي تريدنا التحسين لها؟ (مثل: تكلفة العميل المحتمل، ROAS، CTR، CPA)",
  brief_ph_anything_else_past_experiences_specific_requirements_references: "أي شيء آخر؟ خبرات سابقة، متطلبات خاصة، مراجع...",

  // ==================== BRIEF — MARKETING STRATEGY PAGE ====================
  brief_desc_give_us_a_complete_picture_of_your_business_and_where_it_stands_today: "أعطنا صورة كاملة عن عملك ووضعه الحالي.",
  brief_label_business_overview: "نظرة عامة على العمل",
  brief_ph_tell_us_about_your_business_what_you_do_who_you_serve_how_long_youve_been_operating_size_of_team: "أخبرنا عن عملك — ماذا تفعل، لمن تخدم، منذ متى تعمل، حجم الفريق...",
  brief_label_current_marketing_activities: "الأنشطة التسويقية الحالية",
  brief_ph_what_marketing_are_you_currently_doing_eg_social_media_google_ads_content_marketing_print_events: "ما التسويق الذي تفعله حاليًا؟ (مثل: التواصل الاجتماعي، إعلانات Google، التسويق بالمحتوى، المطبوعات، الفعاليات)",
  brief_step_goals_and_challenges: "الأهداف والتحديات",
  brief_desc_where_do_you_want_to_go_and_whats_holding_you_back: "إلى أين تريد الوصول وما الذي يعيقك؟",
  brief_label_revenue_goals: "أهداف الإيرادات",
  brief_ph_what_are_your_revenue_targets_eg_100kmonth_2x_revenue_in_12_months: "ما هي أهداف الإيرادات؟ (مثل: $100K/شهريًا، ضعف الإيرادات في 12 شهرًا)",
  brief_ph_what_are_the_biggest_obstacles_to_your_growth_eg_low_brand_awareness_not_enough_leads_poor_conversion_rates: "ما هي أكبر العقبات أمام نموك؟ (مثل: توعية منخفضة بالعلامة، عدم كفاية العملاء المحتملين، معدلات تحويل ضعيفة)",
  brief_label_growth_goals: "أهداف النمو",
  brief_ph_where_do_you_want_to_be_in_612_months_what_does_success_look_like: "أين تريد أن تكون خلال 6-12 شهرًا؟ كيف يبدو النجاح؟",
  brief_step_audience_and_competition: "الجمهور والمنافسة",
  brief_desc_who_are_you_targeting_and_who_are_you_up_against: "من تستهدف ومن تتنافس معه؟",
  brief_ph_describe_your_ideal_customer_in_detail_demographics_psychographics_behaviors: "صف العميل المثالي بالتفصيل — الديموغرافيا والسيكوجرافيا والسلوكيات",
  brief_ph_list_35_main_competitors_what_are_they_doing_well_where_do_they_fall_short: "اذكر 3-5 منافسين رئيسيين. ما الذي يفعلونه جيدًا؟ أين يختللون؟",
  brief_label_unique_selling_proposition: "مميزة البيع الفريدة",
  brief_ph_what_makes_you_different_from_competitors_why_should_customers_choose_you: "ما الذي يجعلك مختلفًا عن المنافسين؟ لماذا يجب أن يختارك العملاء؟",
  brief_step_budget_and_kpis: "الميزانية ومؤشرات الأداء",
  brief_desc_how_much_are_you_investing_and_what_metrics_matter: "كم تستثمر وما هي المقاييس المهمة؟",
  brief_ph_what_metrics_will_you_judge_success_by_eg_leads_per_month_conversion_rate_revenue_growth_social_engagement: "ما هي المقاييس التي ستقيس بها النجاح؟ (مثل: عملاء محتملون شهريًا، معدل التحويل، نمو الإيرادات، التفاعل الاجتماعي)",
  brief_ph_anything_else_past_experiences_specific_requirements_timeline_expectations: "أي شيء آخر؟ خبرات سابقة، متطلبات خاصة، توقعات الجدول الزمني...",

  // ==================== BRIEF — SEO PAGE ====================
  brief_step_website_and_business: "الموقع والعمل",
  brief_desc_tell_us_about_your_website_and_business_so_we_can_assess_your_seo_needs: "أخبرنا عن موقعك وعملك لتقييم احتياجات SEO.",
  brief_label_website_url: "رابط الموقع",
  brief_ph_httpsyourwebsitecom: "https://yourwebsite.com",
  brief_label_business_category: "فئة العمل",
  brief_select_select_your_category: "اختر فئتك",
  brief_label_target_keywords: "الكلمات المفتاحية المستهدفة",
  brief_ph_list_keywords_you_want_to_rank_for_eg_digital_marketing_agency_dubai_best_fitness_trainer_near_me: "اذكر الكلمات المفتاحية التي تريد الترتيب لها (مثل: 'وكالة تسويق رقمي دبي', 'أفضل مدرب لياقة قريب مني')",
  brief_ph_eg_dubai_uae_worldwide: "مثال: دبي، الإمارات، عالميًا",
  brief_step_current_seo_status: "حالة SEO الحالية",
  brief_desc_what_seo_work_have_you_already_done: "ما عمل SEO الذي قمت به بالفعل؟",
  brief_label_existing_seo_work: "عمل SEO الموجود",
  brief_ph_describe_any_seo_work_done_before_onpage_offpage_link_building_content_creation: "صف أي عمل SEO تم من قبل — على الصفحة، خارج الصفحة، بناء الروابط، إنشاء المحتوى...",
  brief_label_google_search_console: "Google Search Console",
  brief_label_google_analytics: "Google Analytics",
  brief_step_goals_and_priorities: "الأهداف والأولويات",
  brief_desc_what_do_you_want_to_achieve_with_seo: "ماذا تريد تحقيقه من SEO؟",
  brief_label_monthly_goals: "الأهداف الشهرية",
  brief_ph_what_are_your_monthly_trafficranking_goals_eg_rank_on_page_1_for_5_keywords_10k_monthly_visitors: "ما هي أهداف الزيارات/الترتيب الشهرية؟ (مثل: الترتيب في الصفحة الأولى لـ 5 كلمات مفتاحية، 10 آلاف زائر شهريًا)",
  brief_label_priority_pages: "الصفحات ذات الأولوية",
  brief_ph_which_pages_are_most_important_to_rank_eg_homepage_service_pages_blog_posts: "أي الصفحات مهمة للترتيب؟ (مثل: الصفحة الرئيسية، صفحات الخدمات، مقالات المدونة)",
  brief_ph_list_35_competitors_who_rank_well_for_your_target_keywords: "اذكر 3-5 منافسين يترتبون بشكل جيد لكلماتك المفتاحية المستهدفة"
};

// Text map for auto-translation of elements without data-i18n
window.TEXT_MAP_AR = {
  // Navigation
  "Services": "خدماتنا",
  "Portfolio": "أعمالنا",
  "Industries": "القطاعات",
  "Process": "منهجيتنا",
  "Clients": "عملاؤنا",
  "Book a Call": "احجز مكالمة",

  // Hero Section
  "Marketing Agency": "وكالة تسويق",
  "We Build": "نبني",
  "Brands": "علامات تجارية",
  "People Remember": "يحبها الجميع",
  "We transform ideas into attention, trust, and measurable business growth through creative strategy and performance marketing.": "نحوّل الأفكار إلى اهتمام وثقة ونمو עסקי من خلال استراتيجية إبداعية وتسويق أداءي.",
  "Book Strategy Call": "احجز مكالمة استراتيجية",
  "View Portfolio": "شاهد أعمالنا",
  "Clients Worldwide": "عميل حول العالم",
  "Client Retention": "معدل الاحتفاظ",
  "Average ROI": "متوسط العائد",

  // Marquee
  "Social Media": "وسائل التواصل",
  "Brand Identity": "الهوية البصرية",
  "Video Editing": "المونتاج",
  "Paid Ads": "الإعلانات",
  "Graphic Design": "التصميم",
  "Web Design": "تصميم المواقع",
  "Videography": "التصوير المرئي",
  "Photography": "التصوير",
  "Media Buying": "شراء الإعلانات",

  // Services Section
  "What We Do": "ما نقدمه",
  "Services That Drive Results": "خدمات تحقق نتائج",
  "Everything your brand needs to grow, convert, and dominate.": "كل ما تحتاجه علامتك التجارية للنمو والتحويل والتفوق.",

  // Portfolio Section
  "Our Work": "أعمالنا",
  "Results We've Delivered": "نتائج حققناها",
  "All": "الكل",
  "Medical": "طبي",
  "Fitness": "لياقة",
  "Corporate": "مؤسسي",

  // Stats Section
  "Average Client Results": "متوسط نتائج العملاء",
  "Results": "النتائج",
  "We've Delivered": "التي حققناها",

  // Industries Section
  "Who We Serve": "قطاعات نخدمها",
  "Industries We Specialize In": "قطاعات متخصصة",

  // Process Section
  "How We Work": "كيف نعمل",
  "Our Process": "منهجيتنا",

  // Testimonials Section
  "Client Love": "عملاؤنا يحبوننا",
  "What Our Clients Say": "ما يقوله عملاؤنا",

  // CTA Section
  "Ready To Grow Your Business?": "جاهز لتنمية أعمالك؟",
  "Book a free strategy call today. No pressure, no obligation — just a clear plan for your brand's growth.": "احجز مكالمة استراتيجية مجانية اليوم. لا ضغط ولا التزام — فقط خطة واضحة لنمو علامتك التجارية.",
  "Book Free Consultation": "احجز استشارة مجانية",

  // Footer
  "We build brands people remember. Premium marketing agency serving businesses that demand results.": "نبني علامات تجارية يحبها الجميع. وكالة تسويق متميزة تخدم الشركات التي تطلب النتائج.",
  "Start A Project": "ابدأ مشروعك",
  "\u00a9 2026 VIVEDFX. All rights reserved. Built for brands that mean business.": "\u00a9 2026 VIVEDFX. جميع الحقوق محفوظة. مبني للعلامات التجارية الجادة.",
  "Made with \u2764 for brands that dare to stand out.": "صُنع ب\u2764 للعلامات التجارية الجريئة.",
  "Privacy Policy": "سياسة الخصوصية",
  "Terms of Service": "شروط الخدمة",

  // Common Buttons
  "Back to Home": "الرئيسية",
  "View Full Details": "عرض التفاصيل",
  "Previous Service": "الخدمة السابقة",
  "Next Service": "الخدمة التالية",
  "Book Free Strategy Call": "احجز مكالمة استراتيجية مجانية",
  "Contact Us on WhatsApp": "تواصل عبر واتساب",
  "Start Brief": "ابدأ البريف",

  // Service Overview Cards - Social Media
  "Social Media Management": "إدارة وسائل التواصل الاجتماعي",
  "Strategic content creation, community management, and analytics that build audiences and drive engagement.": "إنشاء محتوى استراتيجي وإدارة مجتمعات وتحليلات تبني جماهير وتزيد التفاعل.",

  // Service Overview Cards - Brand Identity
  "Complete visual systems — logos, color palettes, typography, brand guidelines.": "أنظمة بصرية متكاملة — شعارات وألوان وخطوط وأدلة علامة تجارية.",

  // Service Overview Cards - Video Editing
  "Cinematic reels, brand films, testimonials, and short-form content optimized for maximum reach.": "ريلز سينمائية وأفلام علامة تجارية ومراجع ومقاطع قصيرة محسّنة لأقصى انتشار.",

  // Service Overview Cards - Graphic Design
  "Visuals that stop the scroll — ads, banners, print, packaging crafted to convert.": "تصاميم تجذب الانتباه — إعلانات وبانرات ومطبوعات مصممة للتحويل.",

  // Service Overview Cards - Paid Advertising
  "Data-driven Meta, Google, and TikTok ad campaigns engineered for maximum ROI.": "حملات إعلانية على Meta وGoogle وTikTok مصممة لأقصى عائد.",

  // Service Overview Cards - Website Design
  "High-converting, fast, and beautiful websites built to turn visitors into customers.": "مواقع عالية التحويل وسريعة وجميلة مبنية لتحويل الزوار إلى عملاء.",

  // Service Overview Cards - Videography
  "Professional on-ground video production — corporate shoots, events, product videos.": "إنتاج فيديو احترافي — تصوير مؤسسي وفعاليات ومقاطع منتجات.",

  // Service Overview Cards - Photography
  "High-quality product, portrait, and commercial photography.": "تصوير منتجات وبورتريه وتصوير تجاري عالي الجودة.",

  // Service Overview Cards - Media Buying
  "Strategic media planning and buying across TV, digital, and out-of-home channels.": "التخطيط والشراء الاستراتيجي للإعلانات عبر التلفزيون والرقمي.",

  // Homepage Industries
  "Doctors & Clinics": "أطباء وعيادات",
  "Gyms & Fitness Studios": "صالات اللياقة والرياضية",
  "Engineering Companies": "شركات هندسية",
  "Corporate Businesses": "شركات مؤسسية",
  "Restaurants & F&B": "مطاعم والأغذية والمشروبات",
  "Teachers & Educational Centers": "معلمون ومراكز تعليمية",

  // Homepage Process
  "Discovery": "الاكتشاف",
  "Strategy": "الاستراتيجية",
  "Production": "الإنتاج",
  "Launch": "الإطلاق",

  // Homepage Testimonials
  "Dr. Ahmed Hassan": "د. أحمد حسن",
  "Founder, MediCare Plus Clinic": "مؤسس، عيادة ميدي كير بلس",
  "Sarah Mitchell": "سارة ميتشل",
  "Owner, IronEdge Fitness": "مالكة، أيرون إيدج فيتنس",
  "James Okonkwo": "جيمس أوكونكو",
  "CEO, BuildCore Engineering": "الرئيس التنفيذي، بيلد كور هندسة",

  // Stats
  "+150": "+150",
  "98%": "98%",
  "3.8x": "3.8x",
  "+420%": "+420%",
  "+380%": "+380%",
  "+500%": "+500%",
  "+350%": "+350%",
  "+280%": "+280%",
  "+450%": "+450%",
  "+600%": "+600%",
  "+320%": "+320%",
  "-35%": "-35%",
  "-40%": "-40%",

  // Testimonial texts
  "vivedfx completely transformed our clinic's online presence. In 4 months, we went from almost no social engagement to 40,000+ monthly impressions. New patient bookings are up 3x and our brand finally looks as professional as our service.": "vivedfx حوّلت بالكامل حضور عيادتنا عبر الإنترنت. في 4 أشهر انتقلنا من شبه عدم تفاعل اجتماعي إلى أكثر من 40,000 ظهور شهريًا. حجوزات المرضى الجدد ارتفعت 3 مرات وأخيرًا تبدو علامتنا التجارية احترافية كالخدمة التي نقدمها.",
  "Our gym membership doubled in 6 months after vivedfx launched our rebrand and ad campaigns. The creative work is absolutely fire — our community loves the content and our competitors are clearly watching us now. Best investment we've ever made.": "اشتراكات صالتنا الرياضية تضاعفت في 6 أشهر بعد أن أطلقت vivedfx حملة إعادة التسمية والإعلانات. العمل الإبداعي رائع — مجتمعنا يحب المحتوى وcompetitors يراقبوننا بوضوح الآن. أفضل استثمار قمنا به.",
  "As an engineering firm, we struggled to communicate what we do in a compelling way. vivedfx built us a brand we're genuinely proud of and a website that generates real inbound leads. Revenue from digital channels is up over 200% year-over-year.": "كمكتب هندسي، كنا نعاني من التواصل بما نفعله بطريقة مقنعة. بنت لنا vivedfx علامة تجارية نفخر بها حقًا وموقعًا إلكترونيًا يُولّد عملاء محتملين حقيقيين. الإيرادات من القنوات الرقمية ارتفعت أكثر من 200% مقارنة بالعام السابق.",

  // Process descriptions
  "Deep dive into your business, competitors, and target audience to understand what truly differentiates you.": "غوص عميق في عملك وcompetitors وجمهور المستهدف لفهم ما يميزك حقًا.",
  "Custom roadmap built around your goals — what channels, what content, what budget will drive maximum results.": "خارطة طريق مخصصة حول أهدافك — أي القنوات وأي المحتوى وأي الميزانية ستحقق أقصى نتائج.",
  "World-class creative execution — content, design, video, copy — all produced to the highest standard by our in-house team.": "تنفيذ إبداعي عالمي — محتوى وتصميم وفيديو ونصوص — كلها منتجة بأعلى المعايير من فريقنا الداخلي.",
  "Precision deployment across platforms — every post, ad, and asset published at the optimal time for maximum impact.": "نشر دقيق عبر المنصات — كل منشور وإعلان ومحتوى يُنشر في الوقت المثلي لأقصى تأثير.",

  // Limited Spots / CTA
  "Limited Spots Available": "أماكن محدودة متاحة",
  "Your Business?": "أعمالك؟",

  // Footer
  "© 2026 VIVEDFX. All rights reserved. Built for brands that mean business.": "© 2026 VIVEDFX. جميع الحقوق محفوظة. مبني للعلامات التجارية الجادة.",
  "Made with ❤ for brands that dare to stand out.": "صُنع بـ ❤ للعلامات التجارية الجريئة.",
  "Privacy Policy": "سياسة الخصوصية",
  "Terms of Service": "شروط الخدمة",
  "View All Services": "عرض جميع الخدمات",

  // Footer links and form
  "Services": "خدماتنا",
  "Industries": "القطاعات",
  "Start A Project": "ابدأ مشروعك",

  // ==================== SOCIAL MEDIA (sm) ====================
  "sm_hero_title": "إدارة وسائل التواصل الاجتماعي",
  "sm_hero_desc": "إنشاء محتوى استراتيجي وإدارة مجتمعات وتحليلات تبني جماهير وتزيد التفاعل.",
  "Why Choose Us": "لماذا تختارنا",
  "Engagement Increase": "زيادة التفاعل",
  "Follower Growth": "نمو المتابعين",
  "To Measurable Results": "لنتائج ملموسة",
  "What We Deliver": "ما نقدمه",
  "Content Strategy — Full monthly content calendars tailored to your brand voice.": "استراتيجية المحتوى — تقويم محتوى شهري مخصص لصوت علامتك التجارية.",
  "Daily Posting — Consistent posting across all platforms.": "نشر يومي — نشر منتظم عبر جميع المنصات.",
  "Community Management — Responding to comments and DMs.": "إدارة المجتمعات — الرد على التعليقات والرسائل.",
  "Monthly Analytics — Detailed performance insights.": "تحليلات شهرية — رؤى أداء مفصلة.",
  "Visual Content Creation — Scroll-stopping graphics and carousels.": "إنشاء محتوى بصري — تصاميم وكاروسيل تجذب الانتباه.",
  "Hashtag Research — Strategic hashtag sets for maximum reach.": "بحث الهاشتاغات — مجموعات هاشتاغات استراتيجية لأقصى انتشار.",
  "Audit": "التدقيق",
  "Create": "الإنشاء",
  "Publish": "النشر",
  "Optimize": "التحسين",
  "Results & Benefits": "النتائج والمزايا",
  "More Engaged Followers": "متابعين أكثر تفاعلًا",
  "Stronger Brand Authority": "سلطة علامة تجارية أقوى",
  "Higher Website Traffic": "زيارات موقع أعلى",
  "Better Customer Relationships": "علاقات أفضل بالعملاء",
  "Time Freedom": "حرية الوقت",
  "Data-Driven Growth": "نمو قائم على البيانات",
  "Frequently Asked Questions": "الأسئلة الشائعة",
  "Which platforms do you manage?": "ما هي المنصات التي تديرونها؟",
  "We manage Instagram, Facebook, TikTok, LinkedIn, Twitter/X, Pinterest, and YouTube.": "ندير Instagram وFacebook وTikTok وLinkedIn وTwitter/X وPinterest وYouTube.",
  "How many posts do you create per month?": "كم منشور تنشئون شهريًا؟",
  "Depending on your plan, we create 15-30+ posts per month.": "حسب خطتك، ننشئ 15-30+ منشور شهريًا.",
  "Do you handle paid advertising too?": "هل تديرون الإعلانات المدفوعة أيضًا؟",
  "Yes, we offer paid ad management as an add-on service.": "نعم، نقدم إدارة الإعلانات المدفوعة كخدمة إضافية.",
  "How soon will I see results?": "متى سأرى النتائج؟",
  "Most clients see increased engagement within 2-4 weeks.": "معظم العملاء يرون زيادة التفاعل خلال 2-4 أسابيع.",
  "Can I approve content before it's posted?": "هل يمكنني الموافقة على المحتوى قبل النشر؟",
  "Absolutely. We send content calendars for your approval before publishing.": "بالطبع. نرسل تقويمات المحتوى لموافقتك قبل النشر.",
  "Do you write captions and hashtags too?": "هل تكتبون التعليقات والهاشتاغات أيضًا؟",
  "Yes, every post includes professional captions and strategically researched hashtags.": "نعم، كل منشور يتضمن تعليقات احترافية وهاشتاغات بحث استراتيجي.",
  "Ready to Grow?": "جاهز للنمو؟",
  "Contact on WhatsApp": "تواصل عبر واتساب",

  // ==================== BRAND IDENTITY (bi) ====================
  "bi_hero_title": "الهوية البصرية",
  "bi_hero_desc": "أنظمة بصرية متكاملة — شعارات وألوان وخطوط وأدلة علامة تجارية.",
  "Brand Recognition": "التعرف على العلامة",
  "Trust Score Increase": "زيادة ثقة العملاء",
  "Full Brand Delivery": "تسليم الهوية كاملة",
  "Logo Design — Primary, secondary, and icon versions.": "تصميم الشعار — إصدارات رئيسية وثانوية وأيقونة.",
  "Color System — Primary, secondary, and neutral palettes.": "نظام الألوان — ألوان رئيسية وثانوية ومتعادلة.",
  "Typography — Curated font pairings with hierarchy rules.": "الطباعة — مجموعة خطوط منظمة بقواعد التسلسل الهرمي.",
  "Brand Guidelines — Comprehensive consistency document.": "أدلة العلامة — وثيقة اتساق شاملة.",
  "Business Cards & Stationery — Complete print collateral.": "بطاقات أعمال ومطبوعات — مواد مطبوعة متكاملة.",
  "Brand Pattern & Graphics — Visual elements for all touchpoints.": "أنماط ورسومات العلامة — عناصر بصرية لجميع نقاط التماس.",
  "Research": "البحث",
  "Moodboard": "لوحة المزاج",
  "Design": "التصميم",
  "Refine": "التحسين",
  "Deliver": "التسليم",
  "Instant Brand Recognition": "تعرف فوري على العلامة",
  "Professional Market Positioning": "تموضع مهني في السوق",
  "Consistent Visual Identity": "هوية بصرية متسقة",
  "Increased Customer Trust": "ثقة عملاء متزايدة",
  "Competitive Advantage": "ميزة تنافسية",
  "Long-term Brand Value": "قيمة علامة طويلة الأمد",
  "How long does brand identity take?": "كم تستغرق الهوية البصرية؟",
  "Typically 2-4 weeks from discovery to final delivery.": "عادة 2-4 أسابيع من الاكتشاف إلى التسليم النهائي.",
  "Do I own the final designs?": "هل أمتلك التصاميم النهائية؟",
  "Yes, you receive full ownership of all files and source documents.": "نعم، تتلقى ملكية كاملة لجميع الملفات والمستندات المصدرية.",
  "How many revisions are included?": "كم عدد المراجعات المضمنة؟",
  "We include up to 3 rounds of revisions in every project.": "نقدم حتى 3 جولات من المراجعات في كل مشروع.",
  "What file formats do I receive?": "ما هي صيغ الملفات التي أتلقاها؟",
  "AI, EPS, PDF, PNG, JPG, and SVG in all color variations.": "AI وEPS وPDF وPNG وJPG وSVG بجميع تنسيقات الألوان.",
  "Can you work with my existing brand?": "هل يمكنكم العمل مع علامتي الحالية؟",
  "Yes, we can refresh and elevate your existing brand identity.": "نعم، يمكننا تحديث وتحسين هويتك البصرية الحالية.",
  "Do you create brand guidelines?": "هل تنشئون أدلة العلامة؟",
  "Yes, every project includes a comprehensive brand guidelines document.": "نعم، كل مشروع يتضمن وثيقة أداة علامة شاملة.",

  // ==================== VIDEO EDITING (ve) ====================
  "ve_hero_title": "المونتاج",
  "ve_hero_desc": "ريلز سينمائية وأفلام علامة تجارية ومراجع ومقاطع قصيرة محسّنة لأقصى انتشار.",
  "View Increase": "زيادة المشاهدات",
  "Watch Time Growth": "نمو وقت المشاهدة",
  "Fast Turnaround": "سرعة في التسليم",
  "Reels & Short-form — Scroll-stopping vertical content.": "ريلز ومقاطع قصيرة — محتوى عمودي يجذب الانتباه.",
  "Brand Films — Cinematic storytelling for your brand.": "أفلام علامة تجارية — سرد سينمائي لعلامتك التجارية.",
  "Testimonials — Professional customer review videos.": "مراجعات — فيديوهات احترافية لآراء العملاء.",
  "Motion Graphics — Animated overlays and transitions.": "رسوم متحركة — تراكبات وانتقالات متحركة.",
  "Color Grading — Professional cinematic color correction.": "تصحيح الألوان — تصحيح ألوان سينمائي احترافي.",
  "Sound Design — Music selection and audio mixing.": "تصميم الصوت — اختيار موسيقى ومix صوتي.",
  "Brief": "البريف",
  "Review": "المراجعة",
  "Higher Engagement Rates": "معدلات تفاعل أعلى",
  "Professional Brand Image": "صورة علامة تجارية احترافية",
  "Increased Watch Time": "زيادة وقت المشاهدة",
  "Better Content Performance": "أداء محتوى أفضل",
  "Time Savings": "توفير الوقت",
  "Platform-Optimized Content": "محتوى محسّن لكل منصة",
  "What video formats do you deliver?": "ما هي صيغ الفيديو التي تسلمونها؟",
  "We deliver MP4, MOV, and platform-specific formats optimized for each channel.": "نسلم MP4 وMOV وتنسيقات مخصصة لكل منصة.",
  "How long does a typical edit take?": "كم يستغرق المونتاج العادي؟",
  "Standard edits take 3-5 business days. Rush delivery is available.": "المونتاج العادي يستغرق 3-5 أيام عمل. التسليم السريع متاح.",
  "Do you provide revisions?": "هل تقدمون مراجعات؟",
  "Yes, we include up to 3 rounds of revisions with every project.": "نعم، نقدم حتى 3 جولات من المراجعات مع كل مشروع.",
  "Can you match my brand style?": "هل يمكنكم مطابقة نمط علامتي التجارية؟",
  "Absolutely. We adapt our editing style to match your brand guidelines.": "بالطبع. نكيّف أسلوب المونتاج ليتوافق مع أدلتك التجارية.",
  "Do you handle voiceovers?": "هل تتعاملون مع التعليقات الصوتية؟",
  "Yes, we can arrange professional voiceover services in multiple languages.": "نعم، يمكننا ترتيب خدمات تعليق صوتي احترافي بلغات متعددة.",
  "What if I need ongoing video editing?": "ماذا لو احتجت إلى مونتاج مستمر؟",
  "We offer monthly retainer packages for continuous video content needs.": "نقدم حزم شهرية للحصول على محتوى فيديو مستمر.",

  // ==================== GRAPHIC DESIGN (gd) ====================
  "gd_hero_title": "التصميم الجرافيكي",
  "gd_hero_desc": "تصاميم تجذب الانتباه — إعلانات وبانرات ومطبوعات مصممة للتحويل.",
  "Conversion Increase": "زيادة التحويل",
  "Click-Through Rate": "معدل النقر",
  "Quick Delivery": "تسليم سريع",
  "Social Media Graphics — Posts, stories, and covers.": "تصميم منشورات التواصل — منشورات وقصص وغلاف.",
  "Ad Creatives — Banners and display ads.": "إعلانات — بانرات وdisplay ads.",
  "Print Design — Brochures, flyers, and posters.": "تصميم مطبوعات — كتيبات ونقوط وملصقات.",
  "Packaging Design — Product packaging and labels.": "تصميم التغليف — تغليف وتسميات المنتجات.",
  "Presentation Design — Professional slide decks.": "تصميم العروض — عروض تقديمية احترافية.",
  "Icon Sets — Custom icon libraries.": "مجموعات أيقونات — مكتبات أيقونات مخصصة.",
  "Concept": "المفهوم",
  "Professional Visual Identity": "هوية بصرية احترافية",
  "Higher Conversion Rates": "معدلات تحويل أعلى",
  "Consistent Brand Presentation": "عرض علامة تجارية متسق",
  "Faster Content Production": "إنتاج محتوى أسرع",
  "Multi-Format Delivery": "تسليم بعدة صيغ",
  "Scalable Design Systems": "أنظمة تصميم قابلة للتوسيع",
  "What design formats do you provide?": "ما هي صيغ التصميم التي تقدمونها؟",
  "PSD, AI, PDF, PNG, JPG, and source files as requested.": "PSD وAI وPDF وPNG وJPG وملفات المصدر حسب الطلب.",
  "How many concepts do you present?": "كم مفهومًا تقدمونه؟",
  "We typically present 2-3 concepts per project for your selection.": "نقدم عادة 2-3 مفاهيم لكل مشروع لاختيارك.",
  "Do you offer rush design services?": "هل تقدمون خدمات تصميم سريعة؟",
  "Yes, we offer expedited delivery for urgent projects at an additional fee.": "نعم، نقدم تسليمًا مسرّعًا للمشاريع العاجلة برسوم إضافية.",
  "Can you match my existing brand guidelines?": "هل يمكنكم مطابقة أدلتك التجارية الحالية؟",
  "Absolutely. We ensure all designs align with your brand standards.": "بالطبع. نتأكد أن جميع التصاميم تتوافق مع معايير علامتك التجارية.",
  "Do you provide print-ready files?": "هل تقدمون ملفات جاهزة للطباعة؟",
  "Yes, all print designs include CMYK files with bleed and crop marks.": "نعم، جميع التصاميم المطبوعة تتضمن ملفات CMYK مع فراغ وعلامات القص.",
  "What if I need design revisions later?": "ماذا لو احتجت إلى مراجعات تصميم لاحقًا؟",
  "We offer flexible revision packages for ongoing design needs.": "نقدم حزم مرونة للمراجعات لاحتياجات التصميم المستمرة.",

  // ==================== PAID ADVERTISING (pa) ====================
  "pa_hero_title": "الإعلانات المدفوعة",
  "pa_hero_desc": "حملات إعلانية على Meta وGoogle وTikTok مصممة لأقصى عائد.",
  "Average ROAS": "متوسط العائد على الإنفاق",
  "Cost Per Acquisition": "تكلفة العميل",
  "Revenue Growth": "نمو الإيرادات",
  "Campaign Strategy — Full-funnel advertising plans.": "استراتيجية الحملة — خطط إعلانية شاملة.",
  "Ad Creation — Copy, visuals, and video ads.": "إنشاء الإعلانات — نصوص ومرئيات وفيديو.",
  "Audience Targeting — Precision demographic targeting.": "استهداف الجمهور — استهداف دقيق حسب الديموغرافيا.",
  "A/B Testing — Continuous creative optimization.": "اختبار A/B — تحسين مستمر للإعلانات.",
  "Performance Reports — Weekly analytics and insights.": "تقارير الأداء — تحليلات وأفكار أسبوعية.",
  "Retargeting — Win-back campaigns for lost visitors.": "إعادة الاستهداف — حملات استرداد للزوار المفقودين.",
  "Scale": "التوسيع",
  "Lower Cost Per Click": "تكلفة نقرة أقل",
  "Better Return on Ad Spend": "عائد أفضل على الإنفاق الإعلاني",
  "Qualified Lead Generation": "توليد عملاء مؤهلين",
  "Scalable Ad Campaigns": "حملات إعلانية قابلة للتوسيع",
  "Data-Driven Decisions": "قرارات قائمة على البيانات",
  "Which ad platforms do you manage?": "ما هي منصات الإعلانات التي تديرونها؟",
  "Meta (Facebook/Instagram), Google Ads, TikTok Ads, and LinkedIn Ads.": "Meta (Facebook/Instagram) وGoogle Ads وTikTok Ads وLinkedIn Ads.",
  "What's the minimum ad budget?": "ما هو الحد الأدنى لميزانية الإعلانات؟",
  "We recommend a minimum of $1,000/month for effective campaigns.": "نوصي بحد أدنى 1,000$ شهريًا للحملات الفعالة.",
  "How do you measure campaign success?": "كيف تقيسون نجاح الحملة؟",
  "We track ROAS, CPA, CTR, conversions, and custom KPIs aligned with your goals.": "نتتبع ROAS وCPA وCTR والتحويلات ومؤشرات الأداء المخصصة.",
  "How often will I receive reports?": "كم مرة سأتلقى التقارير؟",
  "Weekly performance reports with monthly comprehensive reviews.": "تقارير أداء أسبوعية مع مراجعات شهرية شاملة.",
  "Can I pause campaigns anytime?": "هل يمكنني إيقاف الحملات في أي وقت؟",
  "Yes, you have full control and can pause or adjust campaigns at any time.": "نعم، لديك السيطرة الكاملة ويمكنك الإيقاف أو التعديل في أي وقت.",
  "Do you handle ad creative production?": "هل تتعاملون مع إنتاج الإعلانات؟",
  "Yes, we create all ad copy, visuals, and video content in-house.": "نعم، ننشئ جميع النصوص والمرئيات ومحتوى الفيديو داخليًا.",

  // ==================== WEBSITE DESIGN (wd) ====================
  "wd_hero_title": "تصميم المواقع",
  "wd_hero_desc": "مواقع عالية التحويل وسريعة وجميلة مبنية لتحويل الزوار إلى عملاء.",
  "Uptime Guarantee": "ضمان وقت التشغيل",
  "Fast Delivery": "تسليم سريع",
  "Custom Design — Unique layouts tailored to your brand.": "تصميم مخصص — تخطيطات فريدة مخصصة لعلامتك التجارية.",
  "Responsive Development — Mobile-first approach.": "تطوير متجاوب — نهج يبدأ بالجوال.",
  "SEO Optimization — On-page technical SEO.": "تحسين SEO — تحسين تقني على الصفحة.",
  "CMS Integration — Easy content management.": "دمج CMS — إدارة محتوى سهلة.",
  "E-commerce Setup — Full online store configuration.": "إعداد المتجر الإلكتروني — تكوين متجر إلكتروني كامل.",
  "Speed Optimization — Fast loading performance.": "تحسين السرعة — أداء تحميل سريع.",
  "Discovery": "الاكتشاف",
  "Wireframe": "الإطار السلكي",
  "Develop": "التطوير",
  "Better User Experience": "تجربة مستخدم أفضل",
  "Improved SEO Rankings": "تحسين ترتيب SEO",
  "Mobile-First Design": "تصميم يبدأ بالجوال",
  "Fast Loading Speed": "سرعة تحميل سريعة",
  "Easy Content Management": "إدارة محتوى سهلة",
  "What website platforms do you build on?": "ما هي منصات المواقع التي تبنون عليها؟",
  "WordPress, Shopify, custom HTML/CSS/JS, and headless CMS solutions.": "WordPress وShopify وHTML/CSS/JS مخصص وحلول headless CMS.",
  "How long does a website take to build?": "كم يستغرق بناء الموقع؟",
  "Typically 2-6 weeks depending on complexity and scope.": "عادة 2-6 أسابيع حسب التعقيد والنطاق.",
  "Do you provide hosting?": "هل تقدمون استضافة؟",
  "We can set up and manage hosting for you, or work with your preferred provider.": "يمكننا إعداد وإدارة الاستضافة، أو العمل مع مزودك المفضل.",
  "Will my website be mobile-friendly?": "هل سيكون متوافقًا مع الجوال؟",
  "Absolutely. All our websites are responsive and mobile-optimized.": "بالطبع. جميع مواقعنا متجاوبة ومحسّنة للجوال.",
  "Do you offer website maintenance?": "هل تقدمون صيانة للمواقع؟",
  "Yes, we provide ongoing maintenance and support packages.": "نعم، نقدم حزم صيانة ودعم مستمرة.",
  "Can I update the website myself?": "هل يمكنني تحديث الموقع بنفسي؟",
  "Yes, we build on user-friendly CMS platforms and provide training.": "نعم، نبني على منصات CMS سهلة الاستخدام ونقدم التدريب.",

  // ==================== VIDEOGRAPHY (vg) ====================
  "vg_hero_title": "التصوير المرئي السينمائي",
  "vg_hero_desc": "إنتاج فيديو احترافي — تصوير مؤسسي وفعاليات ومقاطع منتجات.",
  "Engagement Boost": "زيادة التفاعل",
  "Brand Recall Increase": "زيادة تذكر العلامة",
  "Quick Turnaround": "سرعة في التسليم",
  "Corporate Videos — Professional business content.": "فيديوهات مؤسسية — محتوى أعمال احترافي.",
  "Event Coverage — Full event documentation.": "تغطية الفعاليات — توثيق كامل للفعاليات.",
  "Product Videos — Showcase your products in action.": "مقاطع منتجات — عرض منتجاتك أثناء العمل.",
  "Brand Storytelling — Cinematic brand narratives.": "سرد العلامة التجارية — قصص سينمائية لعلامتك.",
  "Interview Videos — Professional talking head content.": "فيديوهات مقابلات — محتوى احترافي للتحدث.",
  "Drone Footage — Aerial perspectives.": "لقطات درون — منظورات جوية.",
  "Planning": "التخطيط",
  "Post-Production": "ما بعد الإنتاج",
  "Professional Production Quality": "جودة إنتاج احترافية",
  "Memorable Brand Content": "محتوى علامة تجارية لا يُنسى",
  "Versatile Content Library": "مكتبة محتوى متعددة الاستخدامات",
  "Higher Audience Engagement": "تفاعل جمهور أعلى",
  "Multi-Platform Content": "محتوى لعدة منصات",
  "Long-Lasting Visual Assets": "أصول بصرية طويلة الأمد",
  "What video formats do you deliver?": "ما هي صيغ الفيديو التي تسلمونها؟",
  "4K, 1080p, and platform-specific formats in MP4, MOV, and ProRes.": "4K و1080p وتنسيقات مخصصة بـ MP4 وMOV وProRes.",
  "Do you provide the production crew?": "هل تقدمون فريق الإنتاج؟",
  "Yes, we handle all production needs including crew, equipment, and logistics.": "نعم، نتعامل مع جميع احتياجات الإنتاج بما في ذلك الفريق والمعدات والlogistics.",
  "How many revision rounds are included?": "كم جولة مراجعة مضمنة؟",
  "We include up to 3 revision rounds in our standard packages.": "نقدم حتى 3 جولات مراجعة في حزمنا المعيارية.",
  "Can you film at my location?": "هل يمكنكم التصوير في مكاني؟",
  "Yes, we film on-location anywhere or in our professional studio.": "نعم، نصور في أي مكان أو في استوديونا الاحترافي.",
  "Do you provide raw footage?": "هل تقدمون اللقطات الخام؟",
  "Raw footage delivery is available as an add-on service.": "تسليم اللقطات الخام متاح كخدمة إضافية.",
  "What's your booking process?": "ما هي عملية الحجز؟",
  "Contact us to discuss your project, receive a quote, and schedule your shoot date.": "تواصل معنا لمناقشة مشروعك وتلقي عرض سعر وحجز موعد التصوير.",

  // ==================== PHOTOGRAPHY (ph) ====================
  "ph_hero_title": "التصوير الفوتوغرافي التجاري",
  "ph_hero_desc": "تصوير منتجات وبورتريه وتصوير تجاري عالي الجودة.",
  "Visual Appeal Increase": "زيادة الجاذبية البصرية",
  "Product Photography — Clean, professional product shots.": "تصوير منتجات — لقطات منتجات نظيفة واحترافية.",
  "Portrait Photography — Professional headshots and team photos.": "تصوير البورتريه — صور رسمية وصور فريق احترافية.",
  "Commercial Shoots — Brand and advertising photography.": "جولات تجارية — تصوير علامة تجارية وإعلاني.",
  "Lifestyle Photography — Authentic brand moments.": "تصوير نمط الحياة — لحظات علامة تجارية حقيقية.",
  "E-commerce Photography — White background product images.": "تصوير المتاجر الإلكترونية — صور منتجات بخلفية بيضاء.",
  "Photo Retouching — Professional post-processing.": "تحسين الصور — معالجة ما بعد احترافية.",
  "Shoot": "التصوير",
  "Edit": "التعديل",
  "Professional Image Quality": "جودة صورة احترافية",
  "Consistent Brand Visuals": "مرئيات علامة تجارية متسقة",
  "Versatile Photo Library": "مكتبة صور متعددة الاستخدامات",
  "Platform-Optimized Images": "صور محسّنة لكل منصة",
  "Fast Turnaround Time": "سرعة تسليم سريعة",
  "How many photos are included per shoot?": "كم عدد الصور المضمنة لكل جلسة تصوير؟",
  "Depending on the package, typically 20-50+ edited photos per session.": "حسب الحزمة، عادة 20-50+ صورة معدّلة لكل جلسة.",
  "Do you provide props and styling?": "هل تقدمون الإكسسوارات والتنسيق؟",
  "Yes, we can arrange product styling and prop sourcing.": "نعم، يمكننا ترتيب تنسيق المنتجات وتجهيز الإكسسوارات.",
  "What file formats do you deliver?": "ما هي صيغ الملفات التي تسلمونها؟",
  "High-resolution JPG, PNG, and RAW files as requested.": "JPG عالي الدقة وPNG وRAW حسب الطلب.",
  "Do you offer on-location shoots?": "هل تقدمون جولات تصوير في الموقع؟",
  "Yes, we shoot on-location or in our professional studio.": "نعم، نصور في الموقع أو في استوديونا الاحترافي.",
  "How long does photo editing take?": "كم يستغرق تحرير الصور؟",
  "Standard delivery is 3-5 business days after the shoot.": "التسليم العادي هو 3-5 أيام عمل بعد التصوير.",
  "Can you match a specific photography style?": "هل يمكنكم مطابقة نمط تصوير محدد؟",
  "Absolutely. Share your vision and we'll match the style perfectly.": "بالطبع. شارك رؤيتك وسنطابق النمط تمامًا.",

  // ==================== MEDIA BUYING (mb) ====================
  "mb_hero_title": "شراء الإعلانات الاستراتيجي",
  "mb_hero_desc": "التخطيط والشراء الاستراتيجي للإعلانات عبر التلفزيون والرقمي.",
  "Media Cost Reduction": "تخفيض تكلفة الإعلانات",
  "Return on Investment": "عائد على الاستثمار",
  "Reach Increase": "زيادة الوصول",
  "Media Planning — Strategic channel selection.": "التخطيط الإعلامي — اختيار استراتيجي للقنوات.",
  "TV Buying — National and local TV placements.": "شراء التلفزيون — أماكن وطنية ومحلية.",
  "Digital Buying — Programmatic and direct placements.": "شراء رقمي — أماكن programmatic ومباشرة.",
  "OOH Campaigns — Billboards and transit advertising.": "حملات OOH — لوحات إعلانية وإعلانات النقل.",
  "Negotiation — Best rates and premium placements.": "التفاوض — أفضل الأسعار والمواقع المميزة.",
  "Performance Tracking — Cross-channel analytics.": "تتبع الأداء — تحليلات عبر القنوات.",
  "Plan": "التخطيط",
  "Buy": "الشراء",
  "Monitor": "المراقبة",
  "Lower Media Costs": "تكاليف إعلانات أقل",
  "Wider Audience Reach": "وصول أوسع للجمهور",
  "Better Placement Quality": "جودة مواقع أفضل",
  "Cross-Channel Synergy": "تناغم عبر القنوات",
  "Data-Driven Planning": "تخطيط قائم على البيانات",
  "Measurable ROI": "عائد على الاستثمار قابل للقياس",
  "What media channels do you cover?": "ما هي القنوات الإعلامية التي تغطونها؟",
  "TV, radio, digital, social, OOH, print, and programmatic advertising.": "التلفزيون والراديو والرقمي وتواصل الاجتماعي وOOH والمطبوعات والإعلانات programmatic.",
  "How do you negotiate media rates?": "كيف تتفاوضون على أسعار الإعلام؟",
  "We leverage our network and volume to secure the best possible rates.": "نستفيد من شبكتنا والحجم للحصول على أفضل الأسعار الممكنة.",
  "Do you handle both planning and buying?": "هل تتعاملون مع التخطيط والشراء معًا؟",
  "Yes, we provide end-to-end media services from strategy to execution.": "نعم، نقدم خدمات إعلامية شاملة من الاستراتيجية إلى التنفيذ.",
  "Can you work with a specific budget?": "هل يمكنكم العمل بميزانية محددة؟",
  "Absolutely. We optimize media plans to maximize results within your budget.": "بالطبع. نحسّن الخطط الإعلامية لتحقيق أقصى نتائج ضمن ميزانيتك.",
  "How do you measure media performance?": "كيف تقيسون أداء الإعلام؟",
  "We track reach, frequency, GRPs, conversions, and custom KPIs.": "نتتبع الوصول والتردد وGRPs والتحويلات ومؤشرات الأداء المخصصة.",
  "Do you provide media reports?": "هل تقدمون تقارير إعلامية؟",
  "Yes, we provide detailed campaign reports with actionable insights.": "نعم، نقدم تقارير حملات مفصلة مع أفكار عملية.",

  // ==================== BRIEF PAGE ====================
  "Progress": "التقدم",
  "Continue": "التالي",
  "Previous": "السابق",
  "Review & Submit": "مراجعة وإرسال",
  "Submit Brief": "إرسال البريف",
  "Save Progress": "حفظ التقدم",
  "Progress saved": "تم الحفظ",
  "Brief Submitted!": "تم إرسال البريف!",
  "Thank you for completing the brief. Our team will review your submission and get back to you within 24 hours.": "شكرًا لك على إكمال البريف. سيراجع فريقنا طلبك ويرد عليك خلال 24 ساعة.",
  "View Services": "شاهد الخدمات",
  "Review Your Brief": "مراجعة البريف",

  // Service page stat wrappers (no text content)
  "bi_stat_1": "",
  "bi_stat_2": "",
  "bi_stat_3": "",
  "gd_stat_1": "",
  "gd_stat_2": "",
  "gd_stat_3": "",
  "mb_stat_1": "",
  "mb_stat_2": "",
  "mb_stat_3": "",
  "pa_stat_1": "",
  "pa_stat_2": "",
  "pa_stat_3": "",
  "ph_stat_1": "",
  "ph_stat_2": "",
  "ph_stat_3": "",
  "sm_stat_1": "",
  "sm_stat_2": "",
  "sm_stat_3": "",
  "ve_stat_1": "",
  "ve_stat_2": "",
  "ve_stat_3": "",
  "vg_stat_1": "",
  "vg_stat_2": "",
  "vg_stat_3": "",
  "wd_stat_1": "",
  "wd_stat_2": "",
  "wd_stat_3": ""
};
